### ISSUE TITLE
`Path` isn't rendering in exported view

### ISSUE THREAD

**Issue by trusis666** [fusetools/fuselibs-public#1005]
[Reported on a forum.](https://www.fusetools.com/community/forums/fuse_studio/path_isnt_rendering_in_exported_view)

I have a simple component that renders out QR code using SVG <Path/>.

This works perfectly when running in preview mode (locally & on device), but it shows nothing when I export that view and embed it in a native app (tested only on iOS so far).

I am attaching isolated component:

https://dsc.cloud/vv/TestProject-standalone.zip - for testing local preview
https://dsc.cloud/vv/TestProject-exported-views.zip - for testing exported view

On a side note, when I mark view for export using <ExportedView/> + ux:Class property on a <Panel/> (as in attached), I am losing ability to preview locally, so I have to keep adding/removing those bits whenever I want to switch between local testing and embedded testing. Documentation doesn't provide answers/hints, am I missing some tricks there?

If necessary, I can provide iOS test project too (however, it doesn't do anything unusual!)

**Comment by nekronos** [comment]
If you want to preview locally, just do:
```xml
<App>
	<ExportedViews>
		<MyClass ux:Template="MyClass" />
	</ExportedViews>

	<Panel ux:Class="MyClass" />

	<MyClass />
</App>
```

**Comment by nekronos** [comment]
Looks like something goes wrong with the native UI implementation of path rendering. As a workaround you can do: 
```xml
<ExportedViews>
    <GraphicsView ux:Template="QRCode">
        <QRCodePanel />
    </GraphicsView>
</ExportedViews>
```

**Comment by mortoray** [comment]
You should be able to test that native rendering using a `NativeViewHost` on the type, without an exported view.

The backend rendering will be the same on the target regardless whether it's Native, GL, or the exported-Native/GL.

**Comment by nekronos** [comment]
@mortoray the native surface test app is working, could there be invalidation issues?

**Comment by mortoray** [comment]
I don't know. How hard is it to setup the test of using this exported view. Do you have a unoproj and XCode project I could use as a reference?  (I've never created a non-fuse mobile app, so don't know how to do that bit)

Invalidation does sound like a likely possibility. But if other exported views work that's a bit weird. Espeically since it's the native controls failing, not the GL ones.

Potentially this relates to a `Viewport`. I assume FuseViews must expose a `Viewport`, but maybe the control isn't finding it.

**Comment by nekronos** [comment]
the issue happens in normal build aswell with this app

**Comment by mortoray** [comment]
The TestProject project works on Android.

**Comment by mortoray** [comment]
This appears to have nothing to do with the FuseViews itself, but something with Native+Path. The NativeSurfaceTestApp also has paths, so it's unusual it's not working here. I'm trying to find an isolated reproduction.

**Comment by mortoray** [comment]
The Native control has no problem displaying the path. I emit the SVG data and made a standalone app. I'm checking the suspected invalidation now, perhaps when `Data` changes the visual is not updated.

**Comment by mortoray** [comment]
```
<App>
	<ClientPanel>
		<NativeViewHost>
			<Path Data="" Color="#000" ux:Name="path"/>
			
			<Button Text="Set" Alignment="BottomCenter">
				<Clicked>
					<Set path.Data="{= qrcode }"/>
				</Clicked>
			</Button>
		</NativeViewHost>
	</ClientPanel>
	<string ux:Global="qrcode" ux:Value="M16 16h8v8h-8zM24 16h8v8h-8zM32 16h8v8h-8zM40 16h8v8h-8zM48 16h8v8h-8zM56 16h8v8h-8zM64 16h8v8h-8zM80 16h8v8h-8zM96 16h8v8h-8zM112 16h8v8h-8zM128 16h8v8h-8zM136 16h8v8h-8zM144 16h8v8h-8zM152 16h8v8h-8zM160 16h8v8h-8zM168 16h8v8h-8zM176 16h8v8h-8zM16 24h8v8h-8zM64 24h8v8h-8zM104 24h8v8h-8zM112 24h8v8h-8zM128 24h8v8h-8zM176 24h8v8h-8zM16 32h8v8h-8zM32 32h8v8h-8zM40 32h8v8h-8zM48 32h8v8h-8zM64 32h8v8h-8zM96 32h8v8h-8zM128 32h8v8h-8zM144 32h8v8h-8zM152 32h8v8h-8zM160 32h8v8h-8zM176 32h8v8h-8zM16 40h8v8h-8zM32 40h8v8h-8zM40 40h8v8h-8zM48 40h8v8h-8zM64 40h8v8h-8zM80 40h8v8h-8zM128 40h8v8h-8zM144 40h8v8h-8zM152 40h8v8h-8zM160 40h8v8h-8zM176 40h8v8h-8zM16 48h8v8h-8zM32 48h8v8h-8zM40 48h8v8h-8zM48 48h8v8h-8zM64 48h8v8h-8zM80 48h8v8h-8zM88 48h8v8h-8zM96 48h8v8h-8zM112 48h8v8h-8zM128 48h8v8h-8zM144 48h8v8h-8zM152 48h8v8h-8zM160 48h8v8h-8zM176 48h8v8h-8zM16 56h8v8h-8zM64 56h8v8h-8zM80 56h8v8h-8zM104 56h8v8h-8zM128 56h8v8h-8zM176 56h8v8h-8zM16 64h8v8h-8zM24 64h8v8h-8zM32 64h8v8h-8zM40 64h8v8h-8zM48 64h8v8h-8zM56 64h8v8h-8zM64 64h8v8h-8zM80 64h8v8h-8zM96 64h8v8h-8zM112 64h8v8h-8zM128 64h8v8h-8zM136 64h8v8h-8zM144 64h8v8h-8zM152 64h8v8h-8zM160 64h8v8h-8zM168 64h8v8h-8zM176 64h8v8h-8zM80 72h8v8h-8zM88 72h8v8h-8zM104 72h8v8h-8zM112 72h8v8h-8zM16 80h8v8h-8zM48 80h8v8h-8zM64 80h8v8h-8zM72 80h8v8h-8zM80 80h8v8h-8zM88 80h8v8h-8zM104 80h8v8h-8zM120 80h8v8h-8zM128 80h8v8h-8zM136 80h8v8h-8zM144 80h8v8h-8zM152 80h8v8h-8zM176 80h8v8h-8zM16 88h8v8h-8zM24 88h8v8h-8zM48 88h8v8h-8zM72 88h8v8h-8zM80 88h8v8h-8zM104 88h8v8h-8zM112 88h8v8h-8zM136 88h8v8h-8zM152 88h8v8h-8zM160 88h8v8h-8zM32 96h8v8h-8zM48 96h8v8h-8zM56 96h8v8h-8zM64 96h8v8h-8zM96 96h8v8h-8zM104 96h8v8h-8zM128 96h8v8h-8zM136 96h8v8h-8zM144 96h8v8h-8zM152 96h8v8h-8zM160 96h8v8h-8zM16 104h8v8h-8zM24 104h8v8h-8zM48 104h8v8h-8zM56 104h8v8h-8zM72 104h8v8h-8zM120 104h8v8h-8zM128 104h8v8h-8zM144 104h8v8h-8zM168 104h8v8h-8zM16 112h8v8h-8zM24 112h8v8h-8zM32 112h8v8h-8zM40 112h8v8h-8zM64 112h8v8h-8zM80 112h8v8h-8zM88 112h8v8h-8zM96 112h8v8h-8zM112 112h8v8h-8zM120 112h8v8h-8zM128 112h8v8h-8zM152 112h8v8h-8zM160 112h8v8h-8zM168 112h8v8h-8zM80 120h8v8h-8zM112 120h8v8h-8zM120 120h8v8h-8zM128 120h8v8h-8zM168 120h8v8h-8zM176 120h8v8h-8zM16 128h8v8h-8zM24 128h8v8h-8zM32 128h8v8h-8zM40 128h8v8h-8zM48 128h8v8h-8zM56 128h8v8h-8zM64 128h8v8h-8zM80 128h8v8h-8zM112 128h8v8h-8zM120 128h8v8h-8zM152 128h8v8h-8zM176 128h8v8h-8zM16 136h8v8h-8zM64 136h8v8h-8zM104 136h8v8h-8zM112 136h8v8h-8zM136 136h8v8h-8zM152 136h8v8h-8zM168 136h8v8h-8zM16 144h8v8h-8zM32 144h8v8h-8zM40 144h8v8h-8zM48 144h8v8h-8zM64 144h8v8h-8zM80 144h8v8h-8zM88 144h8v8h-8zM104 144h8v8h-8zM128 144h8v8h-8zM136 144h8v8h-8zM144 144h8v8h-8zM160 144h8v8h-8zM168 144h8v8h-8zM176 144h8v8h-8zM16 152h8v8h-8zM32 152h8v8h-8zM40 152h8v8h-8zM48 152h8v8h-8zM64 152h8v8h-8zM88 152h8v8h-8zM96 152h8v8h-8zM104 152h8v8h-8zM112 152h8v8h-8zM136 152h8v8h-8zM152 152h8v8h-8zM168 152h8v8h-8zM176 152h8v8h-8zM16 160h8v8h-8zM32 160h8v8h-8zM40 160h8v8h-8zM48 160h8v8h-8zM64 160h8v8h-8zM88 160h8v8h-8zM104 160h8v8h-8zM128 160h8v8h-8zM136 160h8v8h-8zM144 160h8v8h-8zM152 160h8v8h-8zM160 160h8v8h-8zM16 168h8v8h-8zM64 168h8v8h-8zM96 168h8v8h-8zM120 168h8v8h-8zM128 168h8v8h-8zM144 168h8v8h-8zM160 168h8v8h-8zM168 168h8v8h-8zM16 176h8v8h-8zM24 176h8v8h-8zM32 176h8v8h-8zM40 176h8v8h-8zM48 176h8v8h-8zM56 176h8v8h-8zM64 176h8v8h-8zM80 176h8v8h-8zM96 176h8v8h-8zM112 176h8v8h-8zM120 176h8v8h-8zM128 176h8v8h-8zM160 176h8v8h-8zM168 176h8v8h-8zM176 176h8v8h-8z"/>
</App>
```
