### ISSUE TITLE
Horizontal ScrollView inside NativeViewHost does not scroll on Android 

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#1010]
[Initially reported on community](https://www.fusetools.com/community/forums/bug_reports/scrollview_over_nativeviewhost_isnt_working), but the cause appears to be slightly different from what's described there.

Repro:
```
<App>
    <StackPanel Alignment="VerticalCenter" ItemSpacing="30">
        <ScrollView AllowedScrollDirections="Horizontal" Height="100" Background="#000">
            <StackPanel Orientation="Horizontal" ItemSpacing="30">
                <Each Count="10">
                    <Circle Width="80" Height="80" Color="#0f0"/>
                </Each>
            </StackPanel>
        </ScrollView>
        <NativeViewHost>
            <ScrollView AllowedScrollDirections="Horizontal" Height="100" Background="#000">
                <StackPanel Orientation="Horizontal" ItemSpacing="30">
                    <Each Count="10">
                        <Circle Width="80" Height="80" Color="#0f0"/>
                    </Each>
                </StackPanel>
            </ScrollView>
        </NativeViewHost>
    </StackPanel>
</App>
```
The second `ScrollView` there does not scroll on Android (Nexus 5, Android 6) _at all_.
Vertical `ScrollView`s in a similar setup work no problem.

iOS is not affected, it works just fine in all variations.

**Comment by fusebuild** [comment]
The forum thread [ScrollView over NativeViewHost isn't working.](https://www.fusetools.com/community/forums/bug_reports/scrollview_over_nativeviewhost_isnt_working) posted by Junseok Kim was linked to this issue.
