### ISSUE TITLE
When data bindings in JS fail they don't provide the source info

### ISSUE THREAD

**Issue by danhollick** [fusetools/fuselibs-public#1022]
I discovered this while investigating https://github.com/fusetools/Fuse/issues/4700#issuecomment-365908279

When we get the Diagnostic message from the Simulator we don't get the File Source. Chatted with @yupferris and @kusma and it seems to be a fuselibs thing. Not sure about how hard this will be.

**Comment by mortoray** [comment]
We'd need IExpression, and other bindings, to be able to report a UX location in order to fix this.

**Comment by mortoray** [comment]
Blocked by https://github.com/fusetools/fuselibs-public/issues/1022

**Comment by danhollick** [comment]
@mortoray are you saying you are blocked by this or that this is blocked by itself (some sort of existential infinite loop)? Or did you link the wrong issue?

**Comment by mortoray** [comment]
Linked the wrong issue. Fixed it.

**Comment by mortoray** [comment]
Source information is now present in the diagnostics and console error messages. Preview probably needs to implement: https://github.com/fusetools/Fuse/issues/4824
