### ISSUE TITLE
Investigate SwipeGesture trigger point

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#1027]
This may be a defect in non-Active gestures. Or it may require a new feature to set the triggering point (like saying 0.9 instead of 0.5).

https://www.fusetools.com/community/forums/howto_discussions/swipegesture_how_to_disable_the_apparent_auto-comp

**Comment by fusebuild** [comment]
The forum thread [SwipeGesture: how to disable the apparent auto-complete when the Length hasn't been reached](https://www.fusetools.com/community/forums/howto_discussions/swipegesture_how_to_disable_the_apparent_auto-comp) posted by Darrin was linked to this issue.
