### ISSUE TITLE
Double/float conversion issues (with Keyframe-tag)

### ISSUE THREAD

**Issue by gregersn** [fusetools/fuselibs-public#1037]
```    <float ux:Global="AnimTime" ux:Value="2.0" />
    <Panel Width="300" Height="200" Color="Red" ux:Name="MyPanel">
        <Timeline>
            <Change Target="MyPanel.Width">
                <Keyframe Value="250" Time="AnimTime" />
                <Keyframe Value="200" Time="2" />
            </Change>
        </Timeline>
    </Panel>
```

Gives 

> Error : The node 'AnimTime' can not be used here: Unable to convert 'AnimTime' to the required type 'double'

```
    <double ux:Global="AnimTime" ux:Value="2.0" /> <!-- ATT -->
    <Panel Width="300" Height="200" Color="Red" ux:Name="MyPanel">
        <Timeline>
            <Change Target="MyPanel.Width">
                <Keyframe Value="250" Time="AnimTime / 2" /> <!-- ATT -->
                <Keyframe Value="200" Time="2" />
            </Change>
        </Timeline>
    </Panel>
```

Gives a crash on compile, with the error:
> Error E2028: Fuse.Animations.Keyframe and Uno.UX.PropertyObject are not compatible

```
    <double ux:Global="AnimTime" ux:Value="2.0" />
    <Let ux:Name="HalfTime" Value="AnimTime / 2.0" /> <!-- ATT -->
    <Panel Width="300" Height="200" Color="Red" ux:Name="MyPanel">
        <Timeline>
            <Change Target="MyPanel.Width">
                <Keyframe Value="250" Time="HalfTime" /> <!-- ATT -->
                <Keyframe Value="200" Time="2" />
            </Change>
        </Timeline>
    </Panel>
```

Gives error:
> Error : The node 'HalfTime' can not be used here: Unable to convert 'HalfTime' to the required type 'double'

**Comment by mortoray** [comment]
I'm unsure about the first error, I cannot reproduce it on export or in Preview.  The second example I can reproduce the error however.

**Comment by gregersn** [comment]
Seems like the first line of code had fallen out when I entered the example, but if I have this:
`    <float ux:Global="AnimTime" ux:Value="2.0" />`

then I get 
> Error E8001: The node 'AnimTime' can not be used here: Unable to convert 'AnimTime' to the required type 'double

This is in the 1.7 release

**Comment by mortoray** [comment]
I've created a few new issues, and a PR that does a basic fix. It won't correct the `Time="AnimTime"` conversion case, but does correct `AnimTime / 2`. It also provides a workaround to the other issue, since `Time="AnimTime * 1"` will avoid the conversion error.
