### ISSUE TITLE
LineCap doesn't work on Android device

### ISSUE THREAD

**Issue by trusis666** [fusetools/fuselibs-public#1040]
[Reported in a forum](https://www.fusetools.com/community/forums/bug_reports/linecap_doesnt_work).

use Version: 1.7.0, macOS

I used below markup.
```
<VectorLayer>
	<Path ux:Name="Target" Data="M5,5 C9.88320312,11 17.3832031,14 27.5,14 C37.6167969,14 45.1167969,11 50,5" Width="30">
		<Stroke Width="7" Color="#fff" LineCap="Round" LineJoin="Round"/>
	</Path>
</VectorLayer>
```
In studio, it works properly. But, when in device(I checked only android), it doesn't work.

I checked in iOS. It works! It is only android problem.

**Comment by mortoray** [comment]
It looks like the code sets a Butt cap always, which is an error. This shouldn't be hard to fix.
