### ISSUE TITLE
Color functions like in LESS

### ISSUE THREAD

**Issue by trusis666** [fusetools/fuselibs-public#1065]
Requested on a [forum](https://www.fusetools.com/community/forums/feature_requests/color_functions_like_in_less).

@mortoray this one is for you.

Hi everyone! I have one proposition for declarative markup language UX. What you think about color functions like in Less? Such as lighten(), darken(), saturate(), desaturate(), fadein(), fadeout(), fade() spin() and mix(). So what if we transfer this functionality to Fuse like this:

Declarate global color constants
```
<float4 ux:Global="FillColor"  ux:Value="rgba(0.5, 0,   0.25, 0.5)"/>
<float4 ux:Global="GreenColor" ux:Value="hsla(120, 0.5, 0.5,  1.0)"/>
```
Assignment global colors via color transformers
```
<Rectangle Color="Darken(FillColor, 0.2)"/>
<Rectangle Color="Lerp(GreenColor, FillColor, 0.5)"/>
```

**Comment by mortoray** [comment]
Note that we already have `lerp` and float4 produce RGB by default: `(0.5,0,0.25,0.5)` is an RGBA value.

I've often needed this functionality in my demos, so I'll add it.  I may not add all the functions, but some essentials at least.
