### ISSUE TITLE
incompatible grid error when doing ManualTestingApp::Rooting

### ISSUE THREAD

**Issue by kusma** [fusetools/fuselibs-public#1082]
When re-rooting the UI on the Rooting-page of ManualTestingApp on Windows, I get an error about a grid with incompatible layout parameters:

> Error: Error: A grid is using incompatible layout parameters which may result in incorrect layout. A grid using `Default` row or column sizing must have only one row or column, or have a known size. Add a `DefaultRow` or `DefaultColumn` to get the desired sizing. in Fuse.Layouts.GridLayout<C:\Users\erik\src\fuselibs\Source\Fuse.Controls.Panels\Layouts\GridLayout.uno:1014>

**Comment by mortoray** [comment]
This happens even before the rooting/unrooting. Probably just an older Grid layout in the test. I'll fix it.

**Comment by mortoray** [comment]
Without https://github.com/fusetools/fuselibs-public/issues/827 it's really hard to find where this is. :(

**Comment by mortoray** [comment]
It looks like a `DockLayout` maybe asking a non-docked child for its size -- it's not supposed to do that. This triggers the error message on some grids.

**Comment by mortoray** [comment]
Yup, it's DockLayout.  The fix may be a significant performance improvement on some layouts (very common ones). The defect was triggering a natural size request, which can be costly.
