### ISSUE TITLE
ObservableTest.Style fails intermittently

### ISSUE THREAD

**Issue by kusma** [fusetools/fuselibs-public#109]
This happens often during CI, failing otherwise good tests.

[Here's](https://travis-ci.com/fusetools/fuselibs-public/builds/47166993#L3776) an example of a failure.

> FAILED:  Fuse.Controls.Navigation.Test.Fuse.Navigation.Test.TransitionTest.Style
>          Assertion failed in 'Style', at /Users/travis/build/fusetools/fuselibs-> public/Source/Fuse.Controls.Navigation/Tests/Transition.Test.uno:273
>            Expected: 0.4000000000000000
>            But got : 0.4166670000000000

**Comment by mortoray** [comment]
Looks like a precision issue. Those tests probably already have a `frameIncrement` tolerance, so this is liekly just beyond that.

**Comment by kusma** [comment]
I don't know what happened here. I guess I accidentally hit enter or something. There's no such test.
