### ISSUE TITLE
TransitionTest.Style fails intermittently

### ISSUE THREAD

**Issue by kusma** [fusetools/fuselibs-public#110]
This happens often during CI, failing otherwise good tests.

[Here's](https://travis-ci.com/fusetools/fuselibs-public/builds/47166993#L3776) an example of a failure.

> FAILED:  Fuse.Controls.Navigation.Test.Fuse.Navigation.Test.TransitionTest.Style
>          Assertion failed in 'Style', at /Users/travis/build/fusetools/fuselibs-> public/Source/Fuse.Controls.Navigation/Tests/Transition.Test.uno:273
>            Expected: 0.4000000000000000
>            But got : 0.4166670000000000

**Comment by mortoray** [comment]
Another tolerance issue. The test probably has a frameIncrement allowance and needs to also add eroTolerance or a bit more.  I've noticed that some platforms have slightly different values for floats.

**Comment by kusma** [comment]
@mortoray: I'm assigning you since you wrote the test. If you disagree, feel free to reassign to someone more appropriate.

**Comment by kusma** [comment]
@mortoray: Yeah, probably. I'll disable the test for now, and we can look at them in the great future ;)

**Comment by kusma** [comment]
This test has been disabled for now.
