### ISSUE TITLE
Router stops working after using it on first page with nothing to go back to

### ISSUE THREAD

**Issue by trusis666** [fusetools/fuselibs-public#1105]
Reported in [forum](https://www.fusetools.com/community/forums/bug_reports/go_back_stops_working_after_using_it_on_first_page).

Fuse 1.7.3 Preview
Android

When using the back button with nothing to go back to it stops working when navigating to other pages. Happens both on Android phone and in preview mode on local PC.

## Steps to reproduce the problem:
1) In Preview Viewport -> Go back
2) Click Page1, you get to goto_page
3) In Preview Viewport -> Go back (Not going back)

## Code to reproduce:
```
<App>
	<JavaScript>
    function goToPage() {
        console.log("Go page");
        router.push("goto_page");
    }

    module.exports = {
        goToPage : goToPage
    };
	</JavaScript>
	<Router ux:Name="router" />

	<ClientPanel>
	    <Navigator DefaultPath="home">
	        <Page ux:Template="home">
	            <PageControl ux:Name="containerControl">
	                <Page>
	                    <Panel Tapped="{goToPage}">
	                    	<Text Value="Page 1" />
	                    </Panel>
	                </Page>
	            </PageControl>  
	        </Page>
	        <Page ux:Template="goto_page">
	            <PageControl ux:Name="containerControl">
	                <Page>
	                    <Text Value="Page 2" />
	                </Page>
	            </PageControl>  
	        </Page>         
	    </Navigator>
	</ClientPanel>
</App>
```

**Comment by mortoray** [comment]
Can confirm a defect in the "GoUp" logic... would likely be fixed by https://github.com/fusetools/fuselibs-public/issues/1068 where GoUp is just discarded.

**Comment by mortoray** [comment]
This will be resolved by https://github.com/fusetools/fuselibs-public/pull/1107
The default behaviour will not include the broken GoUp
It also adds an option to intercept this action if there is no back.
