### ISSUE TITLE
Missing data context in `args.data` since 1.7.0

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#1109]
[Reported on community](https://www.fusetools.com/community/forums/general/click_handler_arguments_suddenly_undefiend)

Repro:
```
<App>

  <JavaScript>
    function menuButtonClicked(args) {
      console.log("args = " + JSON.stringify(args));
      console.log("testvar = " + args.data.text.value);
    }

    module.exports = {
      menuButtonClicked: menuButtonClicked
    }
  </JavaScript>
  
  <ClientPanel>
    <MenuItem Label="Demo123" Clicked="{menuButtonClicked}">
    </MenuItem>
  </ClientPanel>

  <Rectangle ux:Class="MenuItem" Row="0" Column="0" Color="#030303">
    <string ux:Property="Label"/>

    <JavaScript>
      var Observable = require("FuseJS/Observable");
      var text = this.Label.map(x => 'Label: ' + x);
      module.exports = {
        text: text
      }
    </JavaScript>

    <StackPanel>
      <Text
        Background="#f00"
        Color="#fff"
        FontSize="22"
        Alignment="Center"
        Margin="0,0,0,100"
        Value="{text}">
      </Text>
    </StackPanel>
  </Rectangle>

</App>
```
The `MenuItem` component exposes a data context that holds a `text` variable, which _in theory_ should be available outside of it. Or, at least, it was until 1.7.0.
User reports this works as expected on 1.4, 1.6.0 and 1.6.1, and fails on builds after 1.7, including 1.8 QA.

Affected: local preview on both Windows and macOS. Haven't tested mobile targets.

**Comment by fusebuild** [comment]
The forum thread [Click handler arguments suddenly undefiend](https://www.fusetools.com/community/forums/general/click_handler_arguments_suddenly_undefiend) posted by Wodger was linked to this issue.

**Comment by mortoray** [comment]
This looks like it was relying on an undefined behaviour of context binding in previous releases. The binding to `JavaScript` in this manner was not intended and was causing some defects that needed to be fixed.

To get a context you must use an `Each`, `Instance`, `With`, or a `PageControl` or `Navigator` with page contexts.

**Comment by eksperts** [comment]
Closing ticket, since the cause of this issue was a deliberate and necessary change.
