### ISSUE TITLE
suspicious warnings in Marshal.Test.uno

### ISSUE THREAD

**Issue by kusma** [fusetools/fuselibs-public#1116]
The following warnings seems a bit dodgy:

> Source\Fuse.Marshal\Tests\Marshal.Test.uno(124.54): W4139: 'Fuse.Marshal.Add(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(125.54): W4139: 'Fuse.Marshal.Add(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(126.54): W4139: 'Fuse.Marshal.Add(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(128.56): W4139: 'Fuse.Marshal.Subtract(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(129.56): W4139: 'Fuse.Marshal.Subtract(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(130.56): W4139: 'Fuse.Marshal.Subtract(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(132.56): W4139: 'Fuse.Marshal.Multiply(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(133.56): W4139: 'Fuse.Marshal.Multiply(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(134.56): W4139: 'Fuse.Marshal.Multiply(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(136.56): W4139: 'Fuse.Marshal.Divide(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(137.56): W4139: 'Fuse.Marshal.Divide(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(138.56): W4139: 'Fuse.Marshal.Divide(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(146.50): W4139: 'Fuse.Marshal.Add(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(147.50): W4139: 'Fuse.Marshal.Subtract(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(148.50): W4139: 'Fuse.Marshal.Multiply(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(149.50): W4139: 'Fuse.Marshal.Divide(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(151.56): W4139: 'Fuse.Marshal.Add(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(152.56): W4139: 'Fuse.Marshal.Subtract(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(153.56): W4139: 'Fuse.Marshal.Multiply(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(154.56): W4139: 'Fuse.Marshal.Divide(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(156.55): W4139: 'Fuse.Marshal.Add(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(157.55): W4139: 'Fuse.Marshal.Subtract(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(158.55): W4139: 'Fuse.Marshal.Multiply(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(159.55): W4139: 'Fuse.Marshal.Divide(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(161.53): W4139: 'Fuse.Marshal.Add(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(162.53): W4139: 'Fuse.Marshal.Subtract(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(163.53): W4139: 'Fuse.Marshal.Multiply(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(164.53): W4139: 'Fuse.Marshal.Divide(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(167.68): W4139: 'Fuse.Marshal.Add(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(168.68): W4139: 'Fuse.Marshal.Subtract(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(169.68): W4139: 'Fuse.Marshal.Multiply(object,object)' is obsolete
> Source\Fuse.Marshal\Tests\Marshal.Test.uno(170.68): W4139: 'Fuse.Marshal.Divide(object,object)' is obsolete

In particular, it seems we're *only* testing the obsolete methods here, not the non-obsolete Try-versions... This should be fixed IMO.

**Comment by mortoray** [comment]
Yes. I thought I migrated the tests, or added new ones. I may have missed these ones.
