### ISSUE TITLE
System.OutOfMemoryException on start-up of ManualTestingApp

### ISSUE THREAD

**Issue by kusma** [fusetools/fuselibs-public#1117]
Here's what happens when I try to start ManualTestingApp for .NET on the current master-branch:

> $ ./Stuff/uno build -r -tdotnet Tests/ManualTests/ManualTestingApp/ManualTestingApp.unoproj
> Uno 1.8.0-rc1 (build 6648) Windows 10 x64 e216a4e
> Copyright (C) 2015-2018 Fusetools
> 
> Configuring
> Installing Uno.Data.Xml 1.8.0-rc1
> 3.98 s
> 
> Installing dependencies  0.85 s
> Compiling syntax tree
> Tests\ManualTests\ManualTestingApp\FpsMeter.ux.uno(127.24): W4139: Uno.Content.Fonts.FontFaceImporter is obsolete
> Tests\ManualTests\ManualTestingApp\DefaultTextRenderer.uno(165.78): W4139: Uno.Content.Fonts.CharacterSets is obsolete
> Tests\ManualTests\ManualTestingApp\DefaultTextRenderer.uno(163.22): W4139: Uno.Content.Fonts.BitmapFont is obsolete
> Tests\ManualTests\ManualTestingApp\DefaultTextRenderer.uno(166.18): W4139: Uno.Content.Fonts.BitmapFont is obsolete
> Tests\ManualTests\ManualTestingApp\DefaultTextRenderer.uno(178.16): W4139: Uno.Content.Fonts.TextRenderer is obsolete
> Tests\ManualTests\ManualTestingApp\DefaultTextRenderer.uno(178.48): W4139: Uno.Content.Fonts.SpriteFontShader is obsolete
> Tests\ManualTests\ManualTestingApp\DefaultTextRenderer.uno(179.26): W4139: Uno.Content.Fonts.TextTransform is obsolete
> Tests\ManualTests\ManualTestingApp\DefaultTextRenderer.uno(64.20): W4139: Uno.Content.Fonts.BitmapFont is obsolete
> Tests\ManualTests\ManualTestingApp\DefaultTextRenderer.uno(52.18): W4139: Uno.Content.Fonts.TextRenderer is obsolete
> Tests\ManualTests\ManualTestingApp\DefaultTextRenderer.uno(52.56): W4139: Uno.Content.Fonts.SpriteFontShader is obsolete
> Tests\ManualTests\ManualTestingApp\DefaultTextRenderer.uno(53.28): W4139: Uno.Content.Fonts.TextTransform is obsolete
> Tests\ManualTests\ManualTestingApp\DefaultTextRenderer.uno(183.8): W4139: Uno.Content.Fonts.TextTransform is obsolete
> 1.41 s
> 
> Generating code and data  3.28 s
> 
> Build completed in 9.54 seconds
>    12 warnings
> Error: System.OutOfMemoryException: Out of memory.
>    at Fuse.Elements.ElementAtlas.PinAndValidateFramebuffer(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Caching\ElementAtlas.uno:line 154
>    at Fuse.Elements.ElementBatch.Draw(DrawContext dc, Float4x4 localToClipTransform, Rect scissorRectInClipSpace) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Caching\ElementBatch.uno:line 227
>    at Fuse.Elements.ElementBatcher.Draw(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Caching\ElementBatcher.uno:line 340
>    at Fuse.Elements.Element.DrawNonUnderlayChildren(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Batching.uno:line 96
>    at Fuse.Elements.Element.DrawWithChildren(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Batching.uno:line 113
>    at Fuse.Elements.Element.CompositEffects(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Effects.uno:line 184
>    at Fuse.Elements.Cache.DrawHeuristically(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Caching\Cache.uno:line 83
>    at Fuse.Elements.Element.Composit(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Effects.uno:line 103
>    at Fuse.Elements.Element.Draw(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Drawing.uno:line 105
>    at Fuse.Controls.Panel.Draw(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Controls.Panels\Panel.Freeze.uno:line 208
>    at Fuse.Elements.Element.DrawNonUnderlayChildren(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Batching.uno:line 71
>    at Fuse.Elements.Element.DrawWithChildren(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Batching.uno:line 113
>    at Fuse.Elements.Element.CompositEffects(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Effects.uno:line 184
>    at Fuse.Elements.Cache.DrawHeuristically(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Caching\Cache.uno:line 83
>    at Fuse.Elements.Element.Composit(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Effects.uno:line 103
>    at Fuse.Elements.Element.Draw(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Drawing.uno:line 109
>    at Fuse.Controls.Panel.Draw(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Controls.Panels\Panel.Freeze.uno:line 208
>    at Fuse.Elements.Element.DrawNonUnderlayChildren(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Batching.uno:line 71
>    at Fuse.Elements.Element.DrawWithChildren(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Batching.uno:line 113
>    at Fuse.Elements.Element.CompositEffects(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Effects.uno:line 184
>    at Fuse.Elements.Cache.DrawHeuristically(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Caching\Cache.uno:line 83
>    at Fuse.Elements.Element.Composit(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Effects.uno:line 103
>    at Fuse.Elements.Element.Draw(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Drawing.uno:line 109
>    at Fuse.Controls.Panel.Draw(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Controls.Panels\Panel.Freeze.uno:line 208
>    at Fuse.Elements.Element.DrawNonUnderlayChildren(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Batching.uno:line 71
>    at Fuse.Elements.Element.DrawWithChildren(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Batching.uno:line 113
>    at Fuse.Elements.Element.CompositEffects(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Effects.uno:line 184
>    at Fuse.Elements.Cache.DrawHeuristically(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Caching\Cache.uno:line 83
>    at Fuse.Elements.Element.Composit(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Effects.uno:line 103
>    at Fuse.Elements.Element.Draw(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Elements\Element.Drawing.uno:line 109
>    at Fuse.Controls.Panel.Draw(DrawContext dc) in C:\Users\erik\src\fuselibs\Source\Fuse.Controls.Panels\Panel.Freeze.uno:line 208
>    at Fuse.Desktop.DesktopRootViewport.Draw() in C:\Users\erik\src\fuselibs\Source\Fuse.Desktop\DesktopRootViewport.uno:line 59
> 
> ERROR: DotNet run failed. (pass --trace for stack trace)
> 

Yikes :(

**Comment by mortoray** [comment]
@kusma Were you testing this on Windows? I've run it on OSX and don't get this problem.

**Comment by kusma** [comment]
@mortoray: Yes.

**Comment by kusma** [comment]
@mortoray: I'm struggling with this again, and I just bisected it to 8d626410303c588ad2d73d46c6152e24a2c392d7. So, uh, yeah... seems there's something we need to figure out here :(

**Comment by kusma** [comment]
This happens when inStart abd inEnd are both <0, 0>...

**Comment by kusma** [comment]
This seems to fix the problem for me:
```patch
diff --git a/Source/Fuse.Drawing.Surface/DotNetSurface.uno b/Source/Fuse.Drawing.Surface/DotNetSurface.uno
index 6d00fc5bc2..fc45e03eb8 100644
--- a/Source/Fuse.Drawing.Surface/DotNetSurface.uno
+++ b/Source/Fuse.Drawing.Surface/DotNetSurface.uno
@@ -40,7 +40,12 @@ namespace Fuse.Drawing
 		*/
 		static public float4 AdjustedEndPoints( float4 area, float2 start, float2 end )
 		{
-			var unit = Vector.Normalize(end - start);
+			var diff = end - start;
+			var lengthSquared = Vector.Dot(diff, diff);
+			if (lengthSquared < 1e-10)
+				return float4(0, 0, 1, 1);
+
+			var unit = diff * Math.Sqrt(lengthSquared);
 			var normal = float2(unit.Y,-unit.X);
 			var isSlopeNeg = unit.X * (-unit.Y) < 0;
 			
```

**Comment by kusma** [comment]
OK, this seems like a better fix:

```patch
diff --git a/Source/Fuse.Drawing.Surface/DotNetSurface.uno b/Source/Fuse.Drawing.Surface/DotNetSurface.uno
index 6d00fc5bc2..c71dbd4c25 100644
--- a/Source/Fuse.Drawing.Surface/DotNetSurface.uno
+++ b/Source/Fuse.Drawing.Surface/DotNetSurface.uno
@@ -797,6 +797,9 @@ namespace Fuse.Drawing
 			ColorBlend blend = CreateColorBlend(lg, bounds, float2(startX, startY), float2(endX, endY),
 				out gStart, out gEnd);
 
+			if (Vector.Dot(gStart, gEnd) < 1e-10)
+				return;
+
 			var brush = new LinearGradientBrush(
 				new PointF(gStart.X, gStart.Y),
 				new PointF(gEnd.X, gEnd.Y),
```
