### ISSUE TITLE
Feature request: make install location configurable on Android

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#115]
As requested on community:
https://www.fusetools.com/community/forums/feature_requests/making_apps_movable_to_sd_card_on_android
https://www.fusetools.com/community/forums/howto_discussions/move_the_app_to_external_storage_android

According to [the docs](https://developer.android.com/guide/topics/data/install-location.html), the possibility of an app being moved to external storage is defined by a property on the `manifest` root tag in `AndroidManifest.xml`, like so:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    android:installLocation="preferExternal"
    ... >
```
where the value of that property can be either `preferExternal` or `auto`. The auto option seems to be a sane default. It would be nice if this was configurable in the `"Android"` section in `.unoproj` files.

There are some concerns about when an app can or can not be moved to external storage, and those are covered in the linked docs page too.

**Comment by kusma** [comment]
This would be a uno-issue, not fuselibs.
