### ISSUE TITLE
"Missing Push Notification Entitlement" warning from iTunes connect when not using push

### ISSUE THREAD

**Issue by knatten** [fusetools/fuselibs-public#122]
I uploaded an app to iTunes connect, and got the following email:

> Dear developer,
>
> We have discovered one or more issues with your recent delivery for "<redacted>". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
>
>Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.
>
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
>
> Regards,
>
> The App Store team

I have not done anything in my app to register with a push notification service, and I'm not using the `Fuse.PushNotifications` package. Here's the relevant section of my `.unoproj`:

```
  "Packages": [
  	"Fuse",
  	"FuseJS",
  	 "Fuse.Audio",
  	"Fuse.Vibration"
  ],
```

**Comment by bstrr** [comment]
I have also seen this warning. Luckily it didn't mean anything with regards to actually releasing my app, as it sailed through smoothly.

**Comment by cbaggers** [comment]
We have merged a feature for this in Uno that lets people ad capabilities (and where possible 'entitlements' too) from the unoproj. This will be coming in a future release

**Comment by seanauriti** [comment]
Also encountered this.

**Comment by cbaggers** [comment]
Basic documentation for this have been written and merged, will be appearing on the site soon

**Comment by cbaggers** [comment]
https://www.fusetools.com/docs/native-interop/ios-capabilities
