### ISSUE TITLE
Fuse.Launcher.Maps problem with query strings

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#126]
Initially reported on community: https://www.fusetools.com/community/forums/howto_discussions/fusejsmaps_module_js

The root cause of the problem is that the InterApp call opens a link to `"http://maps.apple.com/maps?q=" + query ...` here: https://github.com/fusetools/fuselibs-public/blob/master/Source/Fuse.Launcher.Maps/Maps/MapsLauncher.uno#L56

There are two potential solutions:
1. URLencode the query on Uno side before calling `LaunchUriiOS`.
2. Change the docs and explain that using `encodeURI()` on the query string in JavaScript when calling the method is required.

The problem manifests itself on iOS, but the Android counterpart uses a `"geo:0,0?q=" + query` scheme, so it might be vulnerable too.

**Comment by kusma** [comment]
When people pass URLs, it should be reasonable to expect them to understand that the URLs needs to actually be valid URLs, which includes correctly encoding them.

Encoding the URI on the Uno-side is both incorrect (correctly encoded URIs are going to get double encoded) and would be a regression.

Simply telling users to pass the URI through `encodeURI()` is not going to help much, as it creates the illusion that this is actually the correct solution, which it is not.

So either we would have to teach users about URI encoding (which I think is a bad solution, there's already a bunch of resources out there), or we just expect them to know what a valid URI is. I (obviously) think the latter is the better option.

In either case, this is a docs-issue, if an issue at all.

**Comment by kusma** [comment]
(strike that previous comment, that was based on a misunderstanding of the issue)

Yeah, looks like we should do the first, it's unreasonable to expect people to know that the query goes into a URI.

**Comment by kusma** [comment]
There's similar issues with latitude and longitude, by the way. They can both easily contain illegal characters.

**Comment by kusma** [comment]
Also the Android version has problems with not encoding URIs properly.

**Comment by kusma** [comment]
Fuse.Launcher.* seems to be riddled with these issues...

The most depressing thing is seeing [this](https://github.com/fusetools/fuselibs-public/blob/master/Source/Fuse.Launcher.Email/Email/EmailLauncher.uno#L58)... Someone *knew* about encoding-issues, but decided to only solve them for spaces.
