### ISSUE TITLE
UX expression not updating

### ISSUE THREAD

**Issue by nekronos** [fusetools/fuselibs-public#153]
```xml
<Circle ux:Class="MyCircle" Width="80" Height="80" ux:Name="Self">
	<Translation X="{(width(Self) / 2) * -1}" Y="{(height(Self) / 2) * -1}" />
	<Stroke Width="1">
		<SolidColor Color="#000" />
	</Stroke>
</Circle>
```

X and Y on `Translation` is never set

(I know `Anchor="50%,50%"` is the correct way to achieve what I want)

**Comment by Duckers** [comment]
On it!

**Comment by Duckers** [comment]
This is due to the aliasing of `this`. Drop the `ux:Name` and use `this` instead of `Self` and it should be fine. Will fix this for the future, but that's the work-around @nekronos

**Comment by nekronos** [comment]
Ok! :)

**Comment by Duckers** [comment]
Also, drop the curlies `{..}` around the expressions. Curlies indicate a data-binding, making it look for `Self` in the data-context instead of in the `ux:` namespace.

**Comment by Duckers** [comment]
This syntax is correct:

```
<Translation X="(width(Self) / 2) * -1" Y="(height(Self) / 2) * -1" />
```

**Comment by Duckers** [comment]
The remaining issue is fixed in https://github.com/fusetools/uno/issues/1193
