### ISSUE TITLE
New WorldTransfrom invalidation broke NativeViewHost

### ISSUE THREAD

**Issue by nekronos** [fusetools/fuselibs-public#154]
```xml
<App>
    <NativeViewHost />
</App>
```
This app crashes at https://github.com/fusetools/fuselibs-public/blob/master/Source/Fuse.Nodes/Visual.WorldTransformInvalidated.uno#L77

https://github.com/fusetools/fuselibs-public/pull/149

**Comment by yupferris** [comment]
cc @mortoray , who I believe suggested that particular change in the PR

**Comment by kusma** [comment]
Those exceptions are super-unhelpful. It should at least be `Fuse.Diagnostics.InternalError()` instead, or at least have some text in it. Empty exceptions isn't going to help *anyone*.

**Comment by mortoray** [comment]
Yeah, not great exceptions, but they did their job in picking up a problem in the new code.

this probably needs a "Regression" flag (we haven't migrated over issue tags yet it seems)

**Comment by kusma** [comment]
Yeah, nobody moved the issue-labels from the old repo. I can do it a bit later if I remember ;)
