### ISSUE TITLE
Lingering cursor bug is back

### ISSUE THREAD

**Issue by yupferris** [fusetools/fuselibs-public#182]
When focusing a `TextBox` and then unfocusing it, its cursor remains visible, although it stops blinking. Likely a bug with caching and the `TextBox` possibly not invalidating its visual properly when losing focus.

![image](https://user-images.githubusercontent.com/3166056/27957919-e94ca7e2-6320-11e7-9b7a-4ddb9815228e.png)

**Comment by yupferris** [comment]
Minimal repro app:

```
<App>
	<StackPanel>
		<TextInput>
			<!-- This rect isn't necessary for repro but helps to make the TextInput visible -->
			<Rectangle Fill="#eee" Layer="Background" />
		</TextInput>
	</StackPanel>
</App>
```

**Comment by kusma** [comment]
Which platform do you observe this on?

**Comment by yupferris** [comment]
Windows in .net

**Comment by yupferris** [comment]
Just tested with release-1.1, problem is there too.

**Comment by yupferris** [comment]
Ok, it only affects `FuseTextEdit`, not `FallbackTextEdit`. Tested by commenting out the harfbuzz lines in the factories. Looking into the difference there.

**Comment by yupferris** [comment]
It seems `InvalidateVisual` from `FuseTextEdit`'s `INotifyFocus.OnFocusLost` impl isn't causing redraw (its `DrawVisual` isn't called after that), which seems a bit odd..

**Comment by yupferris** [comment]
Broken in 81eae3e4, reverting that should fix this.

**Comment by yupferris** [comment]
Fixed in https://github.com/fusetools/fuselibs-public/pull/184
