### ISSUE TITLE
Data-bound MapMarker coordinates snap to screen center instead of the coordinates set when panning

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#188]
Reported on community. Both Android and iOS affected (both preview and build), tested on macOS + standard Fuse 1.0.1 (build 13566) and Fuse 1.1.0 (build 13793) with a local checkout of fuselibs (on master @ 10.07.2017).

Minimal repro included below. When panning, you will see that one marker stays fixed at the correct coordinates, while the other travels across the map, snapping to the very center of the screen.

```
<App>
    <JavaScript>
        var Observable = require("FuseJS/Observable");
        var cityName = Observable();
        var cityLong = Observable();
        var cityLat = Observable();
        cityName.value="Colombo";
        cityLong.value="79.86124300000006";
        cityLat.value="6.9270786";
        module.exports = {cityName,cityLong,cityLat};
    </JavaScript>

    <NativeViewHost >
        <MapView Latitude="{cityLat}" Longitude="{cityLong}" Zoom="10">
            <MapMarker Latitude="6.9270786" Longitude="79.86124300000006" Label="{cityName}" />
            <MapMarker Latitude="{cityLat}" Longitude="{cityLong}" Label="{cityName}" />
        </MapView>
    </NativeViewHost>
</App>
```

**Comment by fusebuild** [comment]
The forum thread [showing map using Observable have a issue. Map marker change every time. ](https://www.fusetools.com/community/forums/general/showing_map_using_observable_have_a_issue_map_mark) posted by Pasindu Dineth Peiris was linked to this issue.

**Comment by eksperts** [comment]
not a bug. details in linked forum post.
