### ISSUE TITLE
index() and offsetIndex() UX expressions do not work in-line Each on preview

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#204]
Fuse 1.1.0 build 13808, macOS.
Affected: all previews.
Not affected: builds.

Repro:
```
<App>
	<JavaScript>
		var items = [1,2,3,4,5,6,7,8,9,10];
		module.exports = {
			items: items
		};
	</JavaScript>
	<StackPanel ItemSpacing="8" Margin="8">
		<Each Items="{items}" Offset="2" Limit="4">
			<Panel Height="48">
				<Text Value="value: {}; index: {= index(this)}; offsetIndex: {= offsetIndex(this)}" Alignment="CenterLeft" />
			</Panel>
		</Each>
	</StackPanel>
</App>
```
Throws `Could not find and Instantiator` in Problems tab.

**Comment by mortoray** [comment]
I think this might be an issue for [Fuse](https://github.com/fusetools/fuse), since we can't reproduce it outside of preview.

**Comment by Duckers** [comment]
@eksperts Does it fail/crash (if so; how? what error?), or just a diagnostic in the problems tab?

**Comment by mortoray** [comment]
This would happen if somehow the subscription to the function is created prior to the `ContextParent` being set by the time it is called.  The function would fail to find the behaviour with `FindBehavior`.

**Comment by eksperts** [comment]
@mortoray it does not crash. It simply does not evaluate the UX expression altogether. It's just the message in Problems tab.

**Comment by eksperts** [comment]
The `Text` nodes are added and visible, so it confirms it once again: it's just the value not being eval'ed.

**Comment by Duckers** [comment]
I found the error: You are saying `index(this)`, where `this` refers to the current `App`. It should be pointing to the `Text` element in question. It works when you put it in a class of its own, because then `this` refers to the element in the `Each`

**Comment by Duckers** [comment]
It is however curious why it behaves differently in preview and in builds, I'll keep investigating that.

**Comment by Duckers** [comment]
@mortoray : It behaves differently in Preview because in preview, `App` is emulated as a `Node` of some sort, which hits this code path:

```
var searchNode = obj as Node ?? _context.Node;
```

I think this should be rewritten using `VarArgFunction` so that `index()` doesn't require any arguments. You just provide one in the unlikely case that you want the index of another element than the current one.

**Comment by eksperts** [comment]
So for now the correct in-line syntax would be:
```
<Each Items="{items}" Offset="2" Limit="4">
	<Panel ux:Name="item">
		<Text Value="value: {}; index: {= index(item)}; offsetIndex: {= offsetIndex(item)}" Alignment="CenterLeft" />
	</Panel>
</Each>
```
while after the proposed change no arguments would be necessary:
```
<Each Items="{items}" Offset="2" Limit="4">
	<Panel ux:Name="item">
		<Text Value="value: {}; index: {= index()}; offsetIndex: {= offsetIndex()}" Alignment="CenterLeft" />
	</Panel>
</Each>
```
is that correct?

**Comment by Duckers** [comment]
yes

**Comment by Duckers** [comment]
You can drop the `ux:Name="item"` then

**Comment by eksperts** [comment]
Or the `Panel` altogether. Edited my post. Thanks!

**Comment by Duckers** [comment]
Note that you don't need to write `{= index()}`, you can simply do `{index()}`

**Comment by Duckers** [comment]
Considering this closed now, except for #205

**Comment by eksperts** [comment]
I'm afraid that `{index(item)}` doesn't work; it throws `{item} not found in data context`. We'll stick to `{=` then for now.

**Comment by Duckers** [comment]
Right, if you are referencing `ux:Name`s you need the `{=`, but I was talking about in the Bright Future when you don't need to refer to the element :)
