### ISSUE TITLE
Go over UX functions and take advantage of VarArgs where appropriate

### ISSUE THREAD

**Issue by Duckers** [fusetools/fuselibs-public#205]
For example, `index(elm)`  should be possible to write as just `index()` when you want to reference the local node. It should also take an extra optional argument; `index(element, instantiator)` where `instantiator` can be different from the most local instantiator. For example when you have nested Each's, you might want an inner element to use the index from the outer Each.

Ref discussions like https://github.com/fusetools/fuselibs-public/issues/204

**Comment by mortoray** [comment]
The forced parameter is a result of https://github.com/fusetools/fuselibs/issues/4199
