### ISSUE TITLE
name-value pairs items in an array are getting duplicated

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#210]
See Expression.Test / ArrayTest on branch https://github.com/mortoray/fuselibs-public/tree/exprarrayerror

```
<Panel ux:Class="UX.Expression.Array">
	<FuseTest.DudElement ArrayValue=' "one", (id: 12), "three", (a:1,b:2) ' ux:Name="arr"/>
</Panel>
```

Value becomes: `(one, (id: 12), three, ((a: 1), (b: 2), (a: 1), (b: 2))) `

**Comment by Duckers** [comment]
Fixed in the above PR for Uno
