### ISSUE TITLE
Backpaddle on DataBinding needing a NameTable

### ISSUE THREAD

**Issue by Duckers** [fusetools/fuselibs-public#213]
`DataBinding` now requires a `NameTable` in order to be able to resolve `Fuse.Reactive.Name` nodes dynamically. This is a quite expensive requirement. Let's rewrite it so names are resolved UX-compile time instead, at the expense of these syntax trees not being reusable. This will generally make it easier to work with expressions in other contexts, too.

**Comment by mortoray** [comment]
When resolved look at (upcoming from my branch) RouterModify.Test.uno/DynamicPath I've commented out a part of that test.

**Comment by Duckers** [comment]
Fixed in the above PR. @mortoray please revisit your RouterModify thing
