### ISSUE TITLE
AccessViolationException in ScriptingTest.ExternalSameObject

### ISSUE THREAD

**Issue by Duckers** [fusetools/fuselibs-public#237]

**Comment by kusma** [comment]
I also get the same issue with ScriptingTest.Memory.

**Comment by kusma** [comment]
I can reproduce this consistently with [this branch](https://github.com/kusma/fuselibs-public/tree/issue-237-reproduction), builing with `git clean -dfx && ./build.bat && ./Stuff/uno --trace test Source/AllTests.unoproj`

**Comment by kusma** [comment]
> OK:      AllTests.Fuse.Scripting.Test.ScriptingTest.ExceptionMessageIsMarshalledToJavaScript (48,013 µs)
> OK:      AllTests.Fuse.Scripting.Test.ScriptingTest.External (46,244 µs)
> OK:      AllTests.Fuse.Scripting.Test.ScriptingTest.ExternalSameObject (91,856 µs)
> 
> Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at Fuse.Scripting.V8.Simple.Value.Release(JSContext context, JSValue value)
>    at Fuse.Scripting.V8.V8SimpleExtensions.Release(JSValue value, JSContext context) in C:\Users\erik\src\fuselibs\Source\Fuse.Scripting.V8\V8SimpleExtensions.uno:line 46
>    at Fuse.Scripting.V8.Function.Finalize() in C:\Users\erik\src\fuselibs\Source\Fuse.Scripting.V8\Function.uno:line 29

**Comment by kusma** [comment]
As you can see, this happens *after* ExternalSameObject has been run, most likey due to something queued up on the JS-thread or something along those lines.

**Comment by kusma** [comment]
I think I found out what happens, and it's a bit ugly:
- Fuse.Scripting.V8.Function uses the finalizer to try to release it's JSValue
- In .NET, finalizers can happen very late.
- In this case, it happens after the context has been disposed, which means it's _context-member is no longer the right JSContext.

This indicates a design-problem in the resource-tracking here. 

This is a "quick band-aid"-patch, that avoids the crash. I think we should include in the 1.1.1-release, unless there's something obviously wrong:
```patch
diff --git a/Source/Fuse.Scripting.V8/Context.uno b/Source/Fuse.Scripting.V8/Context.uno
index 1baeb9e..fe44fa8 100644
--- a/Source/Fuse.Scripting.V8/Context.uno
+++ b/Source/Fuse.Scripting.V8/Context.uno
@@ -18,6 +18,7 @@ namespace Fuse.Scripting.V8
 		internal Function _instanceOf;
 		int _vmDepth;
 		internal Exception _cachedException;
+		internal bool IsDisposed { get; private set; }
 
 		static extern(CIL) Context()
 		{
@@ -140,6 +141,7 @@ namespace Fuse.Scripting.V8
 				_debugger.Dispose();
 				_debugger = null;
 			}
+			IsDisposed = true;
 			_context.Release();
 			_context = default(Simple.JSContext);
 		}
diff --git a/Source/Fuse.Scripting.V8/Function.uno b/Source/Fuse.Scripting.V8/Function.uno
index c3f0c1d..23cb596 100644
--- a/Source/Fuse.Scripting.V8/Function.uno
+++ b/Source/Fuse.Scripting.V8/Function.uno
@@ -25,8 +25,10 @@ namespace Fuse.Scripting.V8
 
 		~Function()
 		{
-			var cxt = _context == null ? default(Simple.JSContext) : _context._context;
-			_function.AsValue().Release(cxt);
+			if (_context == null)
+				_function.AsValue().Release(default(Simple.JSContext));
+			else if (!_context.IsDisposed)
+				_function.AsValue().Release(_context._context);
 		}
 
 		public override object Call(params object[] args)
```

**Comment by kusma** [comment]
After reading the code more closely, I've concluded that this is a slightly better patch:
```patch
diff --git a/Source/Fuse.Scripting.V8/Context.uno b/Source/Fuse.Scripting.V8/Context.uno
index 1baeb9e..fe44fa8 100644
--- a/Source/Fuse.Scripting.V8/Context.uno
+++ b/Source/Fuse.Scripting.V8/Context.uno
@@ -18,6 +18,7 @@ namespace Fuse.Scripting.V8
 		internal Function _instanceOf;
 		int _vmDepth;
 		internal Exception _cachedException;
+		internal bool IsDisposed { get; private set; }
 
 		static extern(CIL) Context()
 		{
@@ -140,6 +141,7 @@ namespace Fuse.Scripting.V8
 				_debugger.Dispose();
 				_debugger = null;
 			}
+			IsDisposed = true;
 			_context.Release();
 			_context = default(Simple.JSContext);
 		}
diff --git a/Source/Fuse.Scripting.V8/Function.uno b/Source/Fuse.Scripting.V8/Function.uno
index c3f0c1d..5795504 100644
--- a/Source/Fuse.Scripting.V8/Function.uno
+++ b/Source/Fuse.Scripting.V8/Function.uno
@@ -25,8 +25,8 @@ namespace Fuse.Scripting.V8
 
 		~Function()
 		{
-			var cxt = _context == null ? default(Simple.JSContext) : _context._context;
-			_function.AsValue().Release(cxt);
+			if (_context != null && !_context.IsDisposed)
+				_function.AsValue().Release(_context._context);
 		}
 
 		public override object Call(params object[] args)
```
Since _context is a weak-reference, it will only be null in the case where the context was already disposed and collected. There's no good reason to try to release on an non-existent context in that case (`default(Simple.JSContext)` seems to be "no context", not some default-context as I first read it as).

So that case is likely to be just as broken, but wasn't the triggering problem here.

This is probably the result of a slightly sloppy memory-loop avoidance patch.
