### ISSUE TITLE
GestureTest.Layer fails

### ISSUE THREAD

**Issue by kusma** [fusetools/fuselibs-public#247]
```
FAILED:  AllTests.Fuse.Gestures.Test.GestureTest.Layer
         Assertion failed in 'Layer', at C:\Users\erik\src\fuselibs\Source\Fuse.Gestures\Tests\Gesture.Test.uno:31
           Expected: null
           But got : Fuse.Controls.PageControl, Name: edgeMain
```

**Comment by mortoray** [comment]
This is not a random failure. This is expected with the merge for the EdgeNAvigator fix that came in 1.1. I couldn't fix this test on that branch since it wasn't there.

**Comment by kusma** [comment]
@mortoray: Oh, OK. Well, it's broken on master now. Would you be able to fix it now?

**Comment by kusma** [comment]
Seems github has gotten more eager in how it closes issues. I just mentioned the issue in a commit message, yet it thought this meant it was closed. Silly github.

Anyway, I pushed a commit that ignored the test. Please un-ignore when it's fixed.
