### ISSUE TITLE
ActivatedTest.PageControlTiming fails randomly

### ISSUE THREAD

**Issue by kusma** [fusetools/fuselibs-public#248]
```
FAILED:  AllTests.Fuse.Navigation.Test.ActivatedTest.PageControlTiming
         Assertion failed in 'PageControlTiming', at C:\Users\erik\src\fuselibs\Source\Fuse.Navigation\Tests\Activated.Test.uno:165
           Expected: 1
           But got : 0
```

**Comment by mortoray** [comment]
I'm waiting on my other PRs to test this. I changed something about how this works, and fixed a related defect.

**Comment by mortoray** [comment]
I can't get this to happen locally on the improved PageControl branch. Doesn't mean it's gone though. :/

**Comment by mortoray** [comment]
This hasn't been reported in a while, so I assume it's stable now.
