### ISSUE TITLE
String cannot be converted to an IArray

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#253]
`<FuseTest.DudElement ArrayValue=" 'one' " ux:Name="a"/>`

Where

`public IArray ArrayValue { get; set; }`

Results in: `E8001: There is nothing named ''one'' in this scope, and no global resources with that alias.`

Test branch: [expr_string_list](https://github.com/mortoray/fuselibs-public/tree/expr_string_list). Test Fuse.Reactive.Expressions / ExpressionFormat.StringList

**Comment by Duckers** [comment]
Fixed in https://github.com/fusetools/fuselibs-public/pull/346
