### ISSUE TITLE
A string sequence is being parsed as a single string

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#254]
A sequence of simple strings is being parsed as a simple compound string:

`Clicked="modifyRoute( 'one', 'two' )"`

I end up getting the string `one', 'two`.

I'm hoping the second test I put in the expr_string_list branch demonstrates it once the first issue is fixed: https://github.com/fusetools/fuselibs-public/issues/253
I'm trying to come up with an isolated test now.

**Comment by Duckers** [comment]
Fixed in https://github.com/fusetools/fuselibs-public/pull/346
