### ISSUE TITLE
Add more colors 

### ISSUE THREAD

**Issue by danhollick** [fusetools/fuselibs-public#268]
When making some of the teaching content, it's really nice to use `Color="Red"` for basic examples. It helps users see a relationship between the code and screenshots a lot better than a hex-code. But the downside is most of the examples end up being really hard to look at. Primary colors on Primary colors.
Can we add the default css colors to the default Uno colors? https://www.w3schools.com/cssref/css_colors.asp

I think they just need to be replaced here?
https://github.com/fusetools/fuselibs-public/blob/master/Source/Fuse.Drawing/Colors.uno

**Comment by kusma** [comment]
@cbaggers: [You added](https://github.com/fusetools/Fuse/commit/2f3ec00b9e51a04abcbbab428988d911cc0a2b0d) the current color-palette back in early 2015. I know it's a lot to ask, and if you don't know, that's totally fine. But do you remember why you chose this particular seemingly arbitrary subset of the CSS color palette?

**Comment by Sunjammer** [comment]
He just looked for the most unemployed, british colors he could find

**Comment by jesusmartinoza** [comment]
I personally like these http://www.flatuicolorpicker.com/

**Comment by yupferris** [comment]
@Sunjammer: hate to be _that guy_, but I'm not so sure some of our office in-jokes are really appropriate on our public repos.

**Comment by mortoray** [comment]
If the purpose of this is just for teaching examples, then the list of names should be stripped to only those that would be understood by a majority of our readers.

In the current PR there are too many names that nobody would know, and nor I doubt any designer would ever refer to.  Things like t`Dark...` names are good, as are `Light...`, as it adding common names like `Crimson` or `NavyBlue`,  but names like `GoldenRod` and `MintCream` are just noise.

**Comment by Duckers** [comment]
The main problem with colors is that everyone has their preference and its really up to the *theme* being used.

So in my opinion, colors are more appropriately added to *theme kits*, such as the Alive kit defining its own colors `Alive.Blue` etc, and Material design defining its own colors `Material.Red` : https://github.com/Duckers/Fuse.MaterialDesign/blob/master/Style/ColorPalette.ux
