### ISSUE TITLE
Array of NVP's being converted to an object at root-level expression

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#274]
The code that converts a list of NVP's into a single object is also triggering at a root level expression such as this:

```<GotoRoute Path=" 'four': (id: 13), 'inner': (a:1,b:2) "/>```

This unfortunately parses as an object with properties `four` and `inner` rather than a list of NVPs.

The NVP conversion should be limited to when an explicit parenthised list of given.

`Path=" 'four': (id: 13), 'inner': (a:1,b:2) "` (Array of NVP)
`Path=" ('four': (id: 13), 'inner': (a:1,b:2)) "` (Object)

`modifyRoute( path: "one", transition: "None" )` (Array of NVP -- assuming a VarArg function)
`modifyRoute( (path: "one", transition: "None") )` (Object)

**Comment by mortoray** [comment]
See also the parsing issues: https://github.com/fusetools/fuselibs-public/issues/254 and https://github.com/fusetools/fuselibs-public/issues/253

**Comment by Duckers** [comment]
Hmm, to me this isn't a straight forward bug. 

What about this expression producing an object that is both `IArray` and `IObject` ? this would make all parties happy

**Comment by mortoray** [comment]
That will work if we agree those two `Path=` constructs are logically the same.  I think we did say this before. You can wrap an expression at the top-level in as many parens as you want and it makes no difference.

 The `modifyRoute` however must be distinct (one is varargs, one is a single argument).

**Comment by Duckers** [comment]
@mortoray : I believe the above PR fixes this, but I don't have a test case. Please verify (and add a test case if applicable)
