### ISSUE TITLE
Make Uno.DateTime a first class citizen in Fuse.Marshal and in/out of JavaScript and Foreign Code

### ISSUE THREAD

**Issue by Duckers** [fusetools/fuselibs-public#291]
In order to be able to make `DatePicker` and `TimePicker` first class components in Fuse.Controls, we need `Uno.DateTime` to be a type that can be easily passed between native code and JavaScript and Foreign code.

This entails:
- Creating helper functions for converting `Uno.DateTime` to Android and iOS' respective datetime types (and cover with tests please)
- Adding `Uno.DateTime` to all relevant things in `Fuse.Marshal`
- Making sure we can pass `Uno.DateTime` to JS and get it as a `Date` there and vice versa. 

Cases that should be tested are at least:
- `<Uno.DateTime ux:Property="Foo"` and then reading that from `this.Foo` in JS
- `Date` in the data context, bound to a property that expect `Uno.DateTime` and taken back into JS.
- A `NativeModule` that can take a `Date` argument from JS and convert it to a `DateTime` using a helper function
- A `ScriptClass` that can do the same
- `Date` in a route parameter ? (not sure if this would make for valid JSON)

**Comment by Duckers** [comment]
You possibly also need to deal with `DateTime` in `ThreadWorker`'s wrapping/unwrapping functions

**Comment by Duckers** [comment]
@kusma Do we have a way of automated testing of foreign code? Or is ManulaTestApp the only way?

**Comment by kusma** [comment]
@Duckers: AutomaticTestApp

**Comment by Duckers** [comment]
Then @yupferris that's probably where the foreign code tests go for this :)

**Comment by yupferris** [comment]
JS-related bits implemented here: https://github.com/fusetools/fuselibs-public/pull/331

**Comment by yupferris** [comment]
Closing this as it's basically done; the work remaining on the native controls is not covered by this ticket
