### ISSUE TITLE
RenderBounds or Caching or Clipping hiding parts of chart (labels and elements)

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#296]
The fuse-samples Charting has items disappear. 

For example:

-  Zoom in/out of `DoubleBarChart`. When zoomed out the second time the blue bars are gone. When zoomed in some labels are missings stimes.
- Zoom in `MixedBarChart`. The X-labels are sometimes missing .
- In a zoomed `MixedBarChart` resize the window, various clippings/misizings happen

Some of the other charts seem to also show lesser symptoms.

This happens with the Stuff on premiumlibs master now, as well as newer Stuff. This does not happen with the `release-0.3` branch in premiumlibs.

**Comment by mortoray** [comment]
This is a reduced example. Shrink the window and parts of the bars start to disappear.  This only happens when there are 10+ bars; recude the count to 9 and it doesn't happen. This would indicate a problem with the atlas batching.

```
<App xmlns:c="Fuse.Charting">
	<JavaScript>
		var Observable = require("FuseJS/Observable")
		function Item( y, label ) {
			this.y = y
			this.label = label
		}
		
		exports.data1 = Observable()
		
		exports.random = function() {
			exports.data1.clear()
			for (var i=0; i <= 10; ++i ) {
				var y = (Math.random() + 0.2) * 100 * (Math.random() > 0.5 ? -1 : 1)
				exports.data1.add( new Item( y, "#" + i ) )
			}
		}
		
		exports.random()
	</JavaScript>
	<c:Plot Margin="5,20,20,10" YAxisSteps="8">
		<c:DataSeries Data="{data1}"/>
		<GridLayout Columns="auto,10,5,1*" Rows="1*,5,10,20"/>
		
		<Panel Row="0" Column="3">
			<c:PlotData SeriesIndex="0">
				<c:PlotBar>
					<Rectangle Alignment="HorizontalCenter" Width="60%"
						Color="#DAA" 
						StrokeColor="#800" StrokeWidth="2"
						CornerRadius="0,0,20,20"/>
				</c:PlotBar>
			</c:PlotData>
		</Panel>
		
	</c:Plot>
</App>
```

**Comment by mortoray** [comment]
I'm having no luck removing the `PlotBar` part. This might indicate the problem relates to the elements changing size dynamically (this is all that PlotBar does, set the various layout properties on a `Panel`)

**Comment by kusma** [comment]
@mortoray: Are you using fuselibs from master? @Duckers changed renderbounds-calculations there quite a bit...

**Comment by Duckers** [comment]
please try this on an older fuselibs version, e.g. `release-1.2`

I've seen similar bugs in much simpler use cases lately

**Comment by Duckers** [comment]
[MortgageCalculatorRealtimeSliderRepro.zip](https://github.com/fusetools/fuselibs-public/files/1179641/MortgageCalculatorRealtimeSliderRepro.zip)

Here is a minimal test case that shows a similar issue. The slider will clip if you drag it all the way to the right.

**Comment by kusma** [comment]
@Duckers: This repro-case is broken in release-1.2, but works in release-1.1. So this is a 1.2 release-blocker.

**Comment by kusma** [comment]
I'll bisect between the two releases.

**Comment by kusma** [comment]
The problematic commit is 7f89944faa3ddfa906a79ce980ba2f7742eaa3d6, which, when looking at it, is not that illogical. The DrawingOffset should change in this case, which we do not deal with. I think a simple revert should be enough.

**Comment by mortoray** [comment]
@kusma The commit message seems to indicate a false assumption was made.

I wonder if some tests of the atlast batching could be written, to cover at least a few of these common cases?

**Comment by kusma** [comment]
Here's the fix:
```patch
diff --git a/Source/Fuse.Elements/Caching/ElementAtlas.uno b/Source/Fuse.Elements/Caching/ElementAtlas.uno
index 285eca6..f6bad27 100644
--- a/Source/Fuse.Elements/Caching/ElementAtlas.uno
+++ b/Source/Fuse.Elements/Caching/ElementAtlas.uno
@@ -65,7 +65,6 @@ namespace Fuse.Elements
 				entry._atlas.RemoveElement(elm);
 			entry._atlas = this;
 			entry.AtlasRect = rect;
-			entry.DrawingOffset = cacheRect.Minimum;
 			_elements.Add(elm);
 
 			_invalidElements++;
@@ -108,10 +107,7 @@ namespace Fuse.Elements
 				return false;
 
 			_spilledPixels += entry.AtlasRect.Area;
-
 			entry.AtlasRect = rect;
-			entry.DrawingOffset = cacheRect.Minimum;
-
 			if (entry.IsValid)
 			{
 				_invalidElements++;
@@ -181,7 +177,8 @@ namespace Fuse.Elements
 					if (!scissorRectInClipSpace.Intersects(visibleRect))
 						continue;
 
-					var offset = (float2)(entry.AtlasRect.Minimum - entry.DrawingOffset) / density;
+					var cachingRect = ElementBatch.GetCachingRect(elm);
+					var offset = (float2)(entry.AtlasRect.Minimum - cachingRect.Minimum) / density;
 					var translation = Matrix.Translation(offset.X, offset.Y, 0);
 					var cc = new OrthographicFrustum{
 						Origin = float2(0, 0), Size = viewport,
diff --git a/Source/Fuse.Elements/Caching/ElementBatch.uno b/Source/Fuse.Elements/Caching/ElementBatch.uno
index 2bf748b..2d15648 100644
--- a/Source/Fuse.Elements/Caching/ElementBatch.uno
+++ b/Source/Fuse.Elements/Caching/ElementBatch.uno
@@ -65,7 +65,6 @@ namespace Fuse.Elements
 		public ElementBatch _batch;
 		public readonly Element _elm;
 		public Recti AtlasRect;
-		public int2 DrawingOffset;
 		public float _opacity;
 		public bool IsValid;
 	}
@@ -321,11 +320,12 @@ namespace Fuse.Elements
 			for (int i = 0; i < elementCount; ++i)
 			{
 				var entry = _elements[i];
+				var cachingRect = ElementBatch.GetCachingRect(entry._elm);
 				var opacity = entry._opacity;
 
 				var transform = entry._elm.LocalTransform;
 				//this calculation assumes the transform is flat (a precondition to caching the element)
-				float2 localOrigin = ((float2)entry.DrawingOffset + CachingRectPaddingAdjustment) * densityScale;
+				float2 localOrigin = ((float2)cachingRect.Minimum + CachingRectPaddingAdjustment) * densityScale;
 				float2 positionOrigin = transform[3].XY + localOrigin.X * transform[0].XY + localOrigin.Y * transform[1].XY;
 				float2 size = ((float2)entry.AtlasRect.Size - CachingRectPaddingAdjustment * 2) * densityScale;
 				float2 right = transform[0].XY * size.X;
```

@mortoray: Yeah, I'll add at least a test-case for this particular failure.

**Comment by kusma** [comment]
This has been fixed.
