### ISSUE TITLE
Uno.DateTime does not contain a member called 'Ticks'

### ISSUE THREAD

**Issue by ckarmy** [fusetools/fuselibs-public#320]
In the last commit (ad9a182) I get:

```
FileSystemInfo.uno(39): E3104: Uno.DateTime does not contain a member called 'Ticks'. Could you be missing a package reference?
/Users/GF/fuselibs-public/Source/Fuse.FileSystem/Uno/IO/FileSystemInfo.uno(39,1): Error E3104: Uno.DateTime does not contain a member called 'Ticks'. Could you be missing a package reference?
(2.6 s)

Build completed in 18.28 seconds
    1 error
```

**Comment by kusma** [comment]
Sounds like you haven't run `build.sh` since the last time uno was updated...

**Comment by ckarmy** [comment]
@kusma yes I run `build.sh`. I check twice :(

**Comment by ckarmy** [comment]
In `10f9bc7` work fine and I don't get the error

**Comment by kusma** [comment]
@ckarmy: This works fine for me, and on CI. I'm pretty sure this is a problem on your end.

**Comment by ckarmy** [comment]
I delete my repo and clone it again and now work! Thanks!

**Comment by kusma** [comment]
It could be possible that doing a `git clean -dfx` would have been enough.

**Comment by ckarmy** [comment]
I do it but don't work

**Comment by kusma** [comment]
Well, that should be equivalent of deleting and re-cloning. But whatever, good to hear that things work for you again!
