### ISSUE TITLE
ScriptMethod and Observable value messages are out-of-order

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#324]
When both setting observable values and calling a function from JS it is required that the relative order is maintained. But it isn't, all the functions are being executed first. We have several callbacks for gestures, in particular scrolling and with Each/Navigation, that depend on this ordering.

```
		exports.step1 = function() {
			exports.b.value = 1
			order.go(2)
			exports.a.value = 3
		}

	<FuseTest.Ordering A="{a}" B="{b}" C="{c}"
		ux:Name="order"/>
```

This should result in update to `B`, then the call to `go`, then the update to `C`.

I created a set of unit tests on my [jsorder branch](https://github.com/fusetools/fuselibs-public/compare/master...mortoray:jsorder?expand=1)

I'm not clear when it regressed.

**Comment by Duckers** [comment]
This may be related to the rewrites of the UpdateManager priority stuff

**Comment by Duckers** [comment]
Confirmed that these tests also fail on `release-1.2`

**Comment by Duckers** [comment]
Confirmed that theste tests also fail on `release-1.1`. Suspecting that this is not a recent regression.

**Comment by Duckers** [comment]
Fixed in the above PR
