### ISSUE TITLE
Text inside NativeViewHost blocks Clicked trigger

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#342]
Fuse 1.1.1 build 13893, macOS.
Affected: iOS preview (build supposedly too).
Not affected: local preview, Android.

Repro:
```
<App>
  <JavaScript>
	function goToSearch(){
	    console.log("go to search");
	}
	function goToMain(){
	    console.log("go to main");
	}
	module.exports = {
	 goToMain: goToMain,
	 goToSearch: goToSearch
	}
  </JavaScript>
  <NativeViewHost>
    <DockPanel>
      <StatusBarBackground Dock="Top" />
      <DockPanel Height="128" Color="#53c296" Dock="Top">
        <Panel Dock="Left" Width="128" Color="#f00" Clicked="{goToSearch}" />
        <Panel Dock="Right" Width="128" Color="#00f" Clicked="{goToMain}" HitTestMode="LocalBounds">
          <Text Value="Test" Width="56" Height="56" Background="#0f0" Alignment="Center" Color="#fff" FontSize="15" />
        </Panel>
      </DockPanel>
    </DockPanel>
  </NativeViewHost>
</App>
```
Both the red and blue panels are expected to call out to JS correctly. Only on iOS, when you click on the green `Text` inside of the blue panel, the click isn't registered.

Setting `HitTestMode="None"` on the `Text` seems to help work around the issue, but the click should be registered without setting that anyway.

**Comment by fusebuild** [comment]
The forum thread [Click which binds to Text doesn't work on NativeView](https://www.fusetools.com/community/forums/howto_discussions/click_which_binds_to_text_doesnt_work_on_nativevie) posted by dhguswns23@naver.com was linked to this issue.

**Comment by kristianhasselknippe** [comment]
@eksperts: I'm unable to reproduce the error. Could you please verify if this is still an issue with fuselibs master?
