### ISSUE TITLE
Docs mistake in FileSystem, missing copy

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#421]
https://github.com/fusetools/fuselibs-public/blob/master/Source/Fuse.FileSystem/FileSystemModule.uno#L659

That should say `copy` not `move`. As a result of this, the copy method doesn't show up [in docs](https://www.fusetools.com/docs/fuse/filesystem/filesystemmodule#section-table-of-contents).

**Comment by eksperts** [comment]
Resolved in https://github.com/fusetools/fuselibs-public/pull/426

**Comment by kusma** [comment]
Fixed and merged!
