### ISSUE TITLE
Add support for 1024x1024 icon in .unoproj

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#429]
Affects iOS release builds. Reported on Slack.

![screen shot 2017-09-04 at 4 19 21 pm](https://user-images.githubusercontent.com/7188878/30048646-db05b6aa-921f-11e7-924a-38cd1299d88d.png)

AppStore now recommends adding a 1024x1024 application icon that is shown on the AppStore for retina devices. Fuse should have an .unoproj setting that allows to specify an icon of that size.

Since recently this was just recommended, but now iOS apps cannot be submitted for review without one, judging from the screenshot above.

**Comment by kusma** [comment]
This isn't a fuselibs issue, it's a uno-issue.

**Comment by eksperts** [comment]
logged where appropriate, closing ticket
