### ISSUE TITLE
UpdateManager Onces don't get processed if there is no frame invalidation

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#452]
UpdateManager.Update is not called if nothing is invalidated (my guess). This can happen with events that get processed the next frame, in particualr `PerformNextFrame`.

Seen on the manual test app page for User Events. clicked "Contaacts" doesn't go back to the previous page. It doesn't "trigger" the change if you change pages in the higher level navigation though. Like something is stalled somehow.

This may affect more than just the Onces, at least NextFrame, and possibly deferred actions if they go into the next frame as well.

**Comment by mortoray** [comment]
Hmm, in isolation this defect doesn't happen!

**Comment by mortoray** [comment]
The issue isn't navigation, or even the trigger. Something is just stalling entirely. Thus I'm giving this critical since it's very unusual.

**Comment by mortoray** [comment]
This is caused by `Update` not being called on DesktopApp. This is because there is nothing which is dirty:

```
		public override bool NeedsRedraw 
		{ 
			get { return DesktopRootViewport.IsDirty; } 
}
```

This would appear to be because `Update` is called by the `UnoGLControl.Render` function.  I'm not clear on what the correct fix is. The quick fix would be to simply have the above function return `true` if there are pending items in the UpdateManager.

**Comment by mortoray** [comment]
This affects basically any page with a ScrollView as well.

**Comment by kusma** [comment]
This seems to behave correctly in `uno build` (from code-inspection), so I assume the problem is with the tool.

**Comment by mortoray** [comment]
This fails on `uno build` with CMAke backend on OSX.
The linked issue indicates it is likely a problem in Preview as well.

**Comment by kusma** [comment]
Just for the sake of a paper-trail, I believe this issue was introduced by ed20a04e66ca57a60c86c384b8bf406cfa5448df.
