### ISSUE TITLE
EdgeNavigator hijacks Page.Activated

### ISSUE THREAD

**Issue by Sunjammer** [fusetools/fuselibs-public#502]
If I put an EdgeNavigator over a PageControl, whenever the EdgeNavigator is invoked any page in the PageControl gets Deactivated, which in some cases trigger transitions inadvertently :(

```
<EdgeNavigator>
		<Panel ux:Name="sidebar" Edge="Left" Width="30%" Margin="0,0,56,0">
			<Shadow ux:Name="shadow" Angle="180" Distance="8" Size="16" Color="#0000" />
			<ActivatingAnimation>
				<Change shadow.Color="#0004" />
				<Change pages.Opacity="0.8" />
			</ActivatingAnimation>
			<SideBar PageControl="pages" TopPage="top" DetailPage="detail" />
		</Panel>

		<PageControl ux:Name="pages" Transition="None">
			<Top ux:Name="top" />
			<Detail ux:Name="detail" />
		</PageControl>
	</EdgeNavigator>
```

**Comment by mortoray** [comment]
The example here is not complete enougth to demonstrate a problem.

**Comment by mortoray** [comment]
Though, as a guess, something like `WhileActive` will deactivate since it's not part of the active page path to root. You can do something like `<WhileActive Path="Local">` to consider only the local path. Or you can add an intervening router to break the chain to the root:

```
<EdgeNavigator>
    <Panel>
         <Router/>
         <PageControl>
```
