### ISSUE TITLE
<Image Url="" /> tag is not working for "Content-Type: image/jpg"

### ISSUE THREAD

**Issue by ianychoi** [fusetools/fuselibs-public#510]
There has been a report from Korean local community - http://cafe.naver.com/fusefactory/142 .

Problem: The following source returns "ImageSource error : 'HttpImageSource-failed-converson'" error on problems tab on Fuse Studio.

```
<App>
	<Panel>
		<Image Url="http://tong.visitkorea.or.kr/cms/resource/23/1989223_image2_1.jpg"/>
	</Panel>
</App>
```

Strangely, almost image URLs work well: e.g., [2] and even downloading the image and uploading it into another web server works well: e.g., [3] .

[1] http://tong.visitkorea.or.kr/cms/resource/23/1989223_image2_1.jpg
[2] http://www.dasprinzip.com/wp/wp-content/uploads/2014/12/fuse_screen04.jpg
[3] http://demo.riv-tech.co.kr:9898/1989223_image2_1.jpg

From my investigation, [1] returns HTTP response with "Content-Type: image/jpg" but [2] and [3] return HTTP response with "Content-Type: image/jpeg".
So I think the problem would be from such content type. In Safari, [2] and [3] URL displays images on Safari, but [1] downloads the image file. On the other hand, Chrome on Windows displays [1], [2], and [3] on the web browser. I cannot find further differences.

I am not too much sure whether the content type should be "image/jpeg" or not, but from my basic search, some web servers use "image/jpg".

If the problem is related with such content type,
Is it the problem from web servers, or would it be easy to also support "Content-Type: image/jpg" ?

**Comment by fusebuild** [comment]
The forum thread [Fuse Image tag  Can not be done ImageSource error: 'HttpImageSource-failed-converson'](https://www.fusetools.com/community/forums/fuse_studio/fuse_image_tag_can_not_be_done_imagesource_error_h) posted by CHUL SEUNG LEE was linked to this issue.

**Comment by kusma** [comment]
@ianychoi: Thanks for digging. `image/jpg` is not an [IANA-registered content-type](https://www.iana.org/assignments/media-types/media-types.xhtml#image), while `image/jpeg` is. So I think the server is mis-configured in this case.

That being said, we should probably be as fault resistant here as we can reasonably be. So perhaps we can fix this to tolerate this, even if the server is mis-configured.

**Comment by yupferris** [comment]
This is a fabulous error report btw. :)

**Comment by kusma** [comment]
This was fixed.
