### ISSUE TITLE
Scrolling stops working after re-rooting UI

### ISSUE THREAD

**Issue by kusma** [fusetools/fuselibs-public#518]
Scrolling stops working after tapping "Switch UI" and "Switch Back" on the "Rooting"-page of ManualTestingApp.

## Steps to reproduce:
1. Start ManualTestingApp
2. Go to "Rooting" page
3. Tap "Switch UI" -> "Switch Back"
4. Go to "ScrollView" page
5. Swipe the page

Originally reported here: fusetools/ManualTestApp#369

**Comment by kusma** [comment]
This was broken in https://github.com/fusetools/fuselibs-public/pull/362.

**Comment by mortoray** [comment]
The user interaaction for scrolling is still working. The animation upon release does not.

**Comment by kusma** [comment]
@mortoray: Yeah, that's correct. I guess I should have clarified that.

**Comment by mortoray** [comment]
It appears `Scroller.OnUnrooted` is never called, which is very bad!  The referenced patch doesn't touch that bit of the code so I'll have to dig around some more to figure out what actually broke.
