### ISSUE TITLE
LinearRangeBehavior should honour RangeControl.UserStep

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#531]
Only CircularRangeBehavior implements this now.

It's a common use-case that keeps coming up and should be simple to implement.

Migrated from: https://github.com/fusetools/fuselibs/issues/1691

**Comment by fusebuild** [comment]
The forum thread [Slider with integer steps?](https://www.fusetools.com/community/forums/general/slider_with_integer_steps_1) posted by Iain was linked to this issue.
