### ISSUE TITLE
Fuse apps on iPhone X

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#534]
[Asked for on Community](https://www.fusetools.com/community/forums/feature_requests/xcode_9_and_iphone_x).

With the new hairline of iPhone X, we should look into how Fuse apps are rendered on one. It is reported that currently the rendering doesn't take advantage of the extra screen real estate. No physical devices at this point, but XCode 9 comes with a Simulator at least.

**Comment by fusebuild** [comment]
The forum thread [Xcode 9 and iPhone X](https://www.fusetools.com/community/forums/feature_requests/xcode_9_and_iphone_x) posted by Luis Rodriguez was linked to this issue.

**Comment by ruudvanham** [comment]
Is there an estimation when this would be supported?

**Comment by kusma** [comment]
No, not yet.

**Comment by badlee** [comment]
Hi everyone,

I resolve it by add to `build/iOS/{BuildType}/{AppName}-Info.plist`
```xml
<key>UILaunchStoryboardName</key>
<string>CDVLaunchScreen</string>
```

For permanent changes edit `/usr/local/share/uno/Packages/UnoCore/1.4.3/Targets/iOS/Yoboresto/Yoboresto-Info.plist` , and add before `</dict>`.
```xml
#if @(Project.iOS.PList.UILaunchStoryboardName:IsSet)
	<key>UILaunchStoryboardName</key>
	<string>@(Project.iOS.PList.UILaunchStoryboardName)</string>
#endif
```
PS: Sorry for my english i'm french speaker.

**Comment by ianychoi** [comment]
A Korea community member shared another solution by adding two additional LaunchImage screens:

[Adding the followings with images into Images.xcassets/contents.json]
```
{
      "extent" : "full-screen",
      "idiom" : "iphone",
      "subtype" : "2436h",
      "filename" : "iPhone_Portrait_iPhoneX_3X.png",
      "minimum-system-version" : "11.0",
      "orientation" : "portrait",
      "scale" : "3x"
    },
    {
      "extent" : "full-screen",
      "idiom" : "iphone",
      "subtype" : "2436h",
      "filename" : "iPhone_Landscape_iPhoneX_3X.png",
      "minimum-system-version" : "11.0",
      "orientation" : "landscape",
      "scale" : "3x"
    },
```

From my testing with adding two images (1125x2436 for iPhone_Portrait_iPhoneX_3X.png and 2436x1125 for iPhone_Landscape_iPhoneX_3X.png), it seems working well :)

[Before]
![screen shot 2017-12-18 at 2 51 24 pm](https://user-images.githubusercontent.com/6965982/34092708-2150390c-e408-11e7-8428-781c15935983.png)

[Launch screen]
![screen shot 2017-12-18 at 3 25 17 pm](https://user-images.githubusercontent.com/6965982/34092717-2c083a0c-e408-11e7-85ab-a60d26fe09ed.png)

[hikr example]
![screen shot 2017-12-18 at 3 24 45 pm](https://user-images.githubusercontent.com/6965982/34092721-341ad042-e408-11e7-930c-cc85363be906.png)

**Comment by kusma** [comment]
@ianychoi: That fix has already been implemented a while ago. But thanks for the input :)
