### ISSUE TITLE
`default` expression for variables that might not exist

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#558]
In preview missing variables, used in bindings, are reported as warnings (`Foo="{notHere}"` reports "notHere is not found").  This is distracting for varibles that might indeed not be there, as they are optional. A `default` expression would let a user mark such variables. It would also be helpful to resovle initial values while waiting for a model value.

`Value="default( {notHere}, 123)"`

**Comment by Sunjammer** [comment]
I like this a lot

**Comment by mortoray** [comment]
One problem case: when an instance is reused it's important that the value goes back to the default if the new context doesn't have the value. Therefore this might not accept an expression, but a string name instead -- or there's a way to get undefined values on context change.

**Comment by kusma** [comment]
We already have this, int the form of the ?? operator. Is that not sufficient?

**Comment by mortoray** [comment]
I thought we did, but forgot it's that operator.  But that might not actually be sufficient for when a page is reused and the context reset. I'll have to investigate.

**Comment by mortoray** [comment]
I'm changing null coalesce to handle this situation as well. `{a} ?? 'hi'` will evaluate to `hi` when `a` is null  and when `a` doesn't exist.
