### ISSUE TITLE
Model value is getting corrupted in Preview

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#565]
I'm clear on what is happening, but the `Value` in the below test app is getting corrupted. Choose "Select" to choose a color then drag the sliders. Occassionaly the color flickers and you can see other sliders go to the 0 value.

[Comp.zip](https://github.com/fusetools/fuselibs-public/files/1375500/Comp.zip)

**Comment by mortoray** [comment]
This only happens in Preview. I'm running on OSX.

**Comment by sebbert** [comment]
I'm unable to reproduce this behavior after applying https://github.com/fusetools/fuselibs-public/pull/664
