### ISSUE TITLE
Model data context is not available on node where Model is declared

### ISSUE THREAD

**Issue by sebbert** [fusetools/fuselibs-public#572]
The databinding on `{bar}` fails in this case:

Foo.js:
```
export default class Foo {
    constructor() {
        this.bar = 123
    }
}
```

Foo.ux:
```
<Panel ux:Class="Foo" Model="Foo" Width="{bar}" />
```

**Comment by mortoray** [comment]
This is valid, it's something we decided a long-time ago that a binding should not check it's child contexts.  Consider that `Model` is adding a `JavaScript` child, and thus `bar` isn't available in the context of the parent.

Given the problems we had, and what we solved before, it's unlikely we'll be able to change this limitation. It's also not something that actually comes up too often in use-cases. And places where it does usually have a workaround.

**Comment by nekronos** [comment]
Closing as this is the expected behavior
