### ISSUE TITLE
Temporal warnings should contain more information

### ISSUE THREAD

**Issue by kristianhasselknippe** [fusetools/fuselibs-public#596]
For example, if a data-binding has not been satisfied, we get the current message in the problems panel in Fuse studio:
```
{foo} not found in data context
```
It would be nice to know who was looking for foo so that i could more easily jump to that spot in my code.

**Comment by kusma** [comment]
@kristianhasselknippe: The Diagnostic we pass to fuse-studio should contain this information already, as the `SourceObject`-member...

**Comment by kristianhasselknippe** [comment]
Ah, i guess this should be a tools ticket then.
