### ISSUE TITLE
`PageControl.ActiveIndex` not updating after a `seekToPath`

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#614]
https://www.fusetools.com/community/forums/bug_reports/pagecontrol_seektopath_issues_after_fuse_130

**Comment by fusebuild** [comment]
The forum thread [pageControl seekToPath issues after fuse 1.3.0](https://www.fusetools.com/community/forums/bug_reports/pagecontrol_seektopath_issues_after_fuse_130) posted by mircea@code11.com was linked to this issue.
