### ISSUE TITLE
Webview doesn't load with URISchemeHandler set

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#617]
[Reported on community](https://www.fusetools.com/community/forums/bug_reports/webview_doesnt_load_with_urischemehandler_set).

Fuse 1.3.0, macOS 10.12.6, tested on Android 6.0.

**Problem: when adding `URISchemeHandler` property to the webview, the webview doesn't load.**

Partial repro:
```
<Page ux:Class="ConfirmationPage" Title="Confirmation">

	<JavaScript>
		var Observable = require( "FuseJS/Observable" )
		var Context = require("Modules/Context");
		var Storage = require("FuseJS/Storage");
		function goToLoginPage() {
			router.push("login", {});
		}

		function onCompleteEvent(){
			router.goto("confirmationComplete",{});	
		}

		module.exports = {
			redirect_url: Context.new_tranx_redirect_url,
			loggedIn: Context.loggedIn,
			onCompleteEvent: onCompleteEvent,
		};	
	</JavaScript>

	<Router ux:Dependency="router" />
		<TitleAreaContent>
			<ResourceString Key="Title" Value="Confirmation Page"/>
		</TitleAreaContent>

		<Busy ux:Name="isBusy" IsActive="false"/>
	
		<StackPanel ux:Name="notLoggedIn" Alignment="Center" ItemSpacing="10">
			<Text Alignment="Center" FontSize="18">Login Required</Text>
			<Text Alignment="Center" FontSize="12">Only account holders can access this section.</Text>
			<TextButton Text="Please log in." FontSize="15" TextColor="#91008D" HoverColor="#666" Alignment="Top" Clicked="{goToLoginPage}"/>
			<AddingAnimation>
				<Scale Factor="0.4" Duration="0.4" Easing="CubicInOut" />
			</AddingAnimation>				
			<RemovingAnimation>
				
			</RemovingAnimation>
		</StackPanel>

		<DockPanel ux:Name="webView">
	        <NativeViewHost>
	            <WebView Dock="Fill" Url="{redirect_url}" URISchemeHandler="{onCompleteEvent}" ZoomEnabled="false"></WebView>
	        </NativeViewHost>
	    </DockPanel>
		
		<WhileTrue Value="{loggedIn}">
			<Set notLoggedIn.Opacity="0"/>
			<Change notLoggedIn.Opacity="0" Duration="0.2"/>
		</WhileTrue>
		<WhileFalse Value="{loggedIn}">
			<Change notLoggedIn.Opacity="1" Duration="0.2"/>
			<Change notLoggedIn.ZOffset="3" Duration="0.2"/>
		
		</WhileFalse>

		<WhileBusy>
	      <Change loadingPanel.Opacity="1" Duration=".2" />
	      <Change loadingPanel.ZOffset="4" Duration=".2" />
	    
	    </WhileBusy>
	    <LoadingIndicator ux:Name="loadingPanel" Opacity="0" ThemeColor="#fff" UnderlayColor="#3A1127" />

	    <RemovingAnimation>
          <Move RelativeTo="Size" Y="-1" Duration="0.4" Easing="CircularInOut" />
        </RemovingAnimation>
        <LayoutAnimation>
          <Move RelativeTo="LayoutChange" Y="1" Duration="0.4" Easing="CircularInOut" />
        </LayoutAnimation>

</Page>
```

**Comment by fusebuild** [comment]
The forum thread [Webview doesn't load with URISchemeHandler set.](https://www.fusetools.com/community/forums/bug_reports/webview_doesnt_load_with_urischemehandler_set) posted by papakay19@gmail.com was linked to this issue.

**Comment by drslem** [comment]
This appears to be a regression in 1.3 as the repro from [this thread](https://www.fusetools.com/community/forums/bug_reports/v13x_build_breaks_simple_webview_location_app_on_a) works nicely in 1.2.2.

**Comment by yupferris** [comment]
`git bisect` shows df7e740c2b6607004c955c5f0d87f04a21809e7c is the first bad commit

**Comment by yupferris** [comment]
I just quickly tried reverting df7e740c2b6607004c955c5f0d87f04a21809e7c from 1.3 and 1.4 and both work fine, so it's safe to say that's the culprit. It looks pretty basic; the quickest solution would be to just revert the commit. I'm not really familiar enough with the logic around the changes to come up with something better, so I'll ping @Sunjammer to take it from here.

**Comment by Sunjammer** [comment]
The intent was to do the string parsing on the uno end rather than doing it twice in native code and clearly this has not worked out right. Reverting that patch should be fine as it was only an esthetic/code quality choice after conferring with mortoray on trying to avoid the code dupe.
