### ISSUE TITLE
WrapPanel inside StackPanel reserves space that it doesn't use

### ISSUE THREAD

**Issue by kusma** [fusetools/fuselibs-public#634]
This UX file should show the problem:
```UX
<App>
	<ScrollView>
		<Rectangle CornerRadius="5" Color="#CCC">
			<StackPanel Orientation="Horizontal" ItemSpacing="5" Margin="5">
				<WrapPanel>
					<Each Count="50">
						<Rectangle Width="50" Height="50" Color="#0f0" Margin="5" />
					</Each>
				</WrapPanel>
			</StackPanel>
		</Rectangle>
	</ScrollView>
</App>
```
This renders like this:
![image](https://user-images.githubusercontent.com/47073/32050655-efec40fc-ba51-11e7-8231-bd1e327f3206.png)

Notice how the elements inside the `WrapPanel` seems to reserve space as if they were wrapped, but ends up being positioned without wrapping. This seems inconsistent.

It's not clear to be if this should wrap or not. But wrapping while reserving but not when laying out can't be right. In my particular use-case, the ideal result would be that it wrapped.

**Comment by kusma** [comment]
Reducing the `Count`-property on `Each` makes the grey panel reduce it's height, seemingly in steps of the `Rectangle`-height.

**Comment by mortoray** [comment]
This is either an error in `RetainXY` or in the users of `RetainXY` when `RetainMaxXY` should potentially also be used.  I'm reasonably certain the source of this defect is in the `StackPanel`.
