### ISSUE TITLE
Models: Navigator isn't navigating

### ISSUE THREAD

**Issue by kristianhasselknippe** [fusetools/fuselibs-public#638]
[ModelsFoo.zip](https://github.com/fusetools/fuselibs-public/files/1418599/ModelsFoo.zip)

Running this project i'm expecting to see "foooooo" on the screen (ClassesPage should have been instantiated).

Unless I've done a mistake or misunderstood how the system works.

**Comment by mortoray** [comment]
There isn't yet a default path on model objects. It's something that still needs to be added. You'll have to manually add a `this.$path = "ClassesPage"` in the `ClassesPage` constructor.

WE had an approach where this worked before, but need to change it. Navigation needs a function it can call to get the classname of the model object. Once we have that we can add this feature back.

**Comment by kristianhasselknippe** [comment]
i though it used the JS class name to instantiate the correct template..? Has this changed?

**Comment by mortoray** [comment]
It will use the ClassName, that is the intent. The mechanism by which that works is mid-progress though now -- it was changed and the change didn't quite complete.

I need a function I can call from PagesMap.GetObjectPath in RouterPage.uno

**Comment by kristianhasselknippe** [comment]
Does this have an issue somewhere? It doesn't seem to be reflected in the documentation.

**Comment by kristianhasselknippe** [comment]
like, is this something that will be fixed? or is $path the way to go for the foreseeable future?

**Comment by mortoray** [comment]
It must be fixed before release. I don't know if I added an issue -- probably not, as it was meant to be a quick change. Please add an issue and mark it high priority.  You can refer to the code I mentioned, somebody can fix it while I'm gone next week then.

**Comment by kristianhasselknippe** [comment]
@mortoray : this was fixed an already merged, right?

**Comment by mortoray** [comment]
yes
