### ISSUE TITLE
It is possible to execute JS from the wrong thread in ThreadWorker's public Push, InsertAt & RemoveAt methods

### ISSUE THREAD

**Issue by cbaggers** [fusetools/fuselibs-public#643]
The use of the cached context here is unsound and should be replaced with explicit context passing.

Also `ThreadWorker`'s public interface should be limited to what is defined by `IThreadWorker` these methods should be moved to a more suitable home. By putting them on the context the context arg could be avoided if that is an issue

**Comment by cbaggers** [comment]
Hooold on... nothing calls these. I'll remove them and make a PR

**Comment by kusma** [comment]
\o/
