### ISSUE TITLE
Password placeholder is hidden by stars when the editor is unfocusedon Android

### ISSUE THREAD

**Issue by petterroea** [fusetools/fuselibs-public#661]
See https://www.fusetools.com/community/forums/bug_reports/inverted_placeholder_in_textinput_android

Expected behavior: placeholder is visible even though the actual text is hidden due to it being a password input

What is happening: The placeholder text is hidden

This only seems to be an issue on Android. Tested on Android 8

**Comment by fusebuild** [comment]
The forum thread [Inverted Placeholder in TextInput (Android)](https://www.fusetools.com/community/forums/bug_reports/inverted_placeholder_in_textinput_android) posted by Cristian Karmy was linked to this issue.

**Comment by kusma** [comment]
This was already fixed in #628
