### ISSUE TITLE
Cannot rotate ManualTestApp on iOS

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#685]
Rotating the device does not cause the app to be rotated (tested the ManualTestApp). I can't see anything in the unoproj file, or in the resulting XCode file that would lock the orientation, nor do I recall us ever wanting to lock the orientation on this app.

I did not test Android.

**Comment by kusma** [comment]
Good catch. This seems to work fine on release-1.4, I'll bisect further.

**Comment by kusma** [comment]
This broke in 5516d6c5d7d48ea41788d2581a9aebcdf07b40fc.

**Comment by kusma** [comment]
@cbaggers: This was the uno-update where feature/ios-appdelegate-window landed, which seems like the most likely candidate to me... Care to take a look?

**Comment by cbaggers** [comment]
Fixed over here https://github.com/fusetools/uno/pull/1437
