### ISSUE TITLE
Test.StatusBarBackgroundTest.AllLayoutTets fails on Android

### ISSUE THREAD

**Issue by kusma** [fusetools/fuselibs-public#691]
```
FAILED:  AllTests.Fuse.Controls.Test.StatusBarBackgroundTest.AllLayoutTets
         Assertion failed in 'DesiredSizeWithMinWidth', at C:\Users\erik\src\fuselibs\Source\Fuse.Common\Tests\FuseTest\ElementLayoutTester.uno:95
           Expected: 100.0000000
           But got : 1000.0000000
```

It seems odd to me that this fails like this on Android, but not on iOS, given that the implementation seems to use the layout-system the same way here.

**Comment by kusma** [comment]
@mortoray: I assigned you, because you know the layout-system better than me. I tried to have a look, but couldn't figure it out.

**Comment by mortoray** [comment]
Calling all layouts tests on this control is wrong -- it's not intended to pass them as it intentionally modifies layout rules for the status bar.  I'll remove the test in a PR.
