### ISSUE TITLE
Possible incorrect use of AddAction from JS thread

### ISSUE THREAD

**Issue by cbaggers** [fusetools/fuselibs-public#705]
@mortoray caught this in `Source/Fuse.Scripting.JavaScript/ThreadWorker.uno`

```
			UpdateManager.AddAction(CheckAndThrow);
```

> This call to AddAction looks like an error. RunInner is being called from the thread, right? The only safe UpdateManager call form a non-UI thread is PostAction.

**Comment by mortoray** [comment]
It looks like `CheckAndThrow` is meant to run in the UI thread, just this call to `AddAction` is from the wrong thread (we currently have no way to add action handlers from another thread).
