### ISSUE TITLE
Models: javascript code out of date if restarting preview app

### ISSUE THREAD

**Issue by nekronos** [fusetools/fuselibs-public#718]
If I preview my app on device, do some JS changes and restart the app without rebuilding. I often get errors referring to the JS code from when I built preview. If I restart the preview app I then have to do a reify triggering change in all my JS files for them to become up-to-date

**Comment by mortoray** [comment]
Is this a fuselibs or Preview issue?

**Comment by nekronos** [comment]
I dont know

**Comment by kristianhasselknippe** [comment]
I've verified that this still happens. Here is a repro case:
[RestartJSError.zip](https://github.com/fusetools/fuselibs-public/files/1487222/RestartJSError.zip)

1. Start RestartJSError in fuse preview
2. Change the value of this.foo in App.js to some other string
3. Observe the value change in the preview viewport
4. Restart the viewport using Viewport -> Restart from the menu
5. Observe that the viewport is now displaying the old value "bar"

**Comment by sebbert** [comment]
This has supposedly been fixed in https://github.com/fusetools/Fuse/pull/4549
