### ISSUE TITLE
Models: preview stuck on loading screen

### ISSUE THREAD

**Issue by nekronos** [fusetools/fuselibs-public#725]
Not sure if this is a preview issue or models issue. At some point I did a new preview build after doing lots of coding on my app and now preview wont start.

Only observed on device as [desktop preview is not working at all currently](https://github.com/fusetools/Fuse/pull/4452)

Repro:
[Archive.zip](https://github.com/fusetools/fuselibs-public/files/1458215/Archive.zip)

**Comment by nekronos** [comment]
Still the case with my test app

**Comment by nekronos** [comment]
Preview stuck at
<img width="788" alt="image" src="https://user-images.githubusercontent.com/1404886/33837061-8199a6f4-de8b-11e7-89a5-43b70de6a9f8.png">

**Comment by nekronos** [comment]
Do not know how to debug

**Comment by sebbert** [comment]
@nekronos Can you verify that this has been fixed?

**Comment by nekronos** [comment]
Works!
