### ISSUE TITLE
Remove dead native shape drawing code

### ISSUE THREAD

**Issue by kristianhasselknippe** [fusetools/fuselibs-public#730]
Since the surface api was introduced, there is a bunch of unused code for drawing native circles and rectangles and such. Here are some examples:

https://github.com/fusetools/fuselibs-public/blob/master/Source/Fuse.Controls.Native/iOS/Circle.uno

https://github.com/fusetools/fuselibs-public/blob/master/Source/Fuse.Controls.Native/iOS/Rectangle.uno

These are no longer in use when drawing native Circles and Rectangles and made it hard to figure out how we actually do draw these shapes in native.

**Comment by nekronos** [comment]
https://github.com/fusetools/fuselibs-public/pull/1058
