### ISSUE TITLE
Fuse gives me error message from the transpiled code

### ISSUE THREAD

**Issue by kristianhasselknippe** [fusetools/fuselibs-public#796]
To reproduce:

Tested on:
Fuse version 1.4.0 (build 14869)

1. Build project in local fuse preview (i tested on windows)
2. Experience error

[problem hikr.zip](https://github.com/fusetools/fuselibs-public/files/1501897/problem.hikr.zip)
Output:
```
[Viewport]: Error: TypeError: _MockBackend2.default.getHikes is not a function: Name: TypeError: _MockBackend2.default.getHikes is not a function
Error message: Uncaught TypeError: _MockBackend2.default.getHikes is not a function
File name: Models/App.js
Line number: 44
Source line: 		_MockBackend2.default.getHikes().then(function (hikes) {
JS stack trace: TypeError: _MockBackend2.default.getHikes is not a function
    at new App (Models/App.js:44:25)
    at (model-script):10:16
    at e.invoke (FuseJS/Internal/zone.min.js:1:21996)
    at r.run (FuseJS/Internal/zone.min.js:1:17156)
    at runInZone (FuseJS/Internal/Model.js:193:20)
    at instrument (FuseJS/Internal/Model.js:31:4)
    at Model (FuseJS/Internal/Model.js:26:2)
    at (model-script):9:18
 in Fuse.Scripting.DiagnosticSubject<Models/App.js:44>

```

**Comment by kristianhasselknippe** [comment]
Note: The project has an actual user error (I'm trying to call getHikes on the class itself, not an instance of the class). But this error isn't being very helpful. And i think we should try to make sure we do not give the user errors from the transpiled code (as far as it is possible).

**Comment by sebbert** [comment]
The transpiled code is what's actually running. Nothing to do about that.

**Comment by kristianhasselknippe** [comment]
@sebbert : Aren't we generating source maps or something for this?

**Comment by kristianhasselknippe** [comment]
Unless this is something we can't ever fix, i don't think we should close this ticket...

**Comment by sebbert** [comment]
Yes, we are generating source maps, but a source map only defines a relation between to lines of code, not language entities. So yes, we can get the line number (and original line of code), but there's nothing to do about the error message itself.

I've scoped down the issue a bit and opened a new ticket here: https://github.com/fusetools/fuselibs-public/issues/814
