### ISSUE TITLE
A Panel with TextInput does not correctly resize in a ScrollView

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#833]
Fuse 1.4.0 build 14778, macOS.
Originally reported [on community](https://www.fusetools.com/community/forums/bug_reports/app_clips_area_where_system_keyboard_was_displayed), same Fuse version on Windows 10.

Affected: both preview and release builds on both Android and iOS (tested on a Nexus 5 with Android 6 and iPhone 6 with iOS 11).

Repro:
```
<App>
    <DockPanel>
        <BottomBarBackground Dock="Bottom" IncludesKeyboard="true" />
        <ScrollView>
            <Panel Width="100%" Height="100%" Background="#18f">
                <Rectangle StrokeWidth="1" StrokeColor="#bdbebf" Padding="2" Alignment="Center" MinWidth="160">
                    <TextInput />
                </Rectangle>
            </Panel>
        </ScrollView>
    </DockPanel>
</App>
```

Testing steps:
1. Run repro in local preview, then run a preview on Android or iOS.
2. Focus the textinput, keyboard shows up.
3. Click outside the textinput, keyboard hides and the blue background again covers 100% of the screen.
4. Focus the textinput, enter a single letter.
5. Click outside the texinput, keyboard hides but the blue background does not resize to cover 100% of the screen.
6. Optional: deleting the content in textinput does not have a further effect, the panel never resizes to 100% height again.

Video of the bug in action: https://www.dropbox.com/s/5qdhce5cwd8sqap/scrollview-bug.mp4?dl=0

**Comment by fusebuild** [comment]
The forum thread [App Clips Area where System Keyboard Was Displayed ](https://www.fusetools.com/community/forums/bug_reports/app_clips_area_where_system_keyboard_was_displayed) posted by Vlad was linked to this issue.

**Comment by mortoray** [comment]
`Height="100%"` is undefined within a vertical `ScrollView` as it doesn't pass a height to it's children. I'm not sure if I have a way to detect this invalid parameter... I'll check.

If such a thing is really required consider this setup instead:

```
<ScrollView ux:Name="s">
   <Panel Height="height(s)">
```

It's a  really weird layout though, as it defeats the purpose of a ScrollView. But it might make sense if this is done deeper within the ScrollView, like on a child of a StackPanel.

**Comment by mortoray** [comment]
After looking at the code I think this was specifically designed so that `HEight="100%"` works, using the contianer relative sizing mode. It fails to update somewhere when the frame size changes though, which is odd.

**Comment by mortoray** [comment]
Notice the position of the input doesn't change either, that's more directly the problem. It's a caching issue in layout it seems. Hopefully the fix doesn't cause performance issues.
