### ISSUE TITLE
LinearGradient direction on Path is incorrect

### ISSUE THREAD

**Issue by drslem** [fusetools/fuselibs-public#841]
Consider this example where the only difference between the 3 paths is a _tiny_ variation of the X coordinate of the `LinearGradient.StartPoint`

Replacing the Path's with Rectangles gives the expected results (e.g. virtually no difference between the 3 instances)

```
<App>
	<Grid RowCount="3">
		<Path Data="M 1 1 L 0 1 L 0 0 L 0 0" StretchMode="Fill" Width="100%" Height="100%" >
			<LinearGradient StartPoint="0.5, 0" EndPoint="0.5, 1">
				<GradientStop Color="#f00" Offset="0" />
				<GradientStop Color="#00f" Offset="1" />
			</LinearGradient>
		</Path>

		<Path Data="M 1 1 L 0 1 L 0 0 L 0 0" StretchMode="Fill" Width="100%" Height="100%" >
			<LinearGradient StartPoint="0.50001, 0" EndPoint="0.5, 1">
				<GradientStop Color="#f00" Offset="0" />
				<GradientStop Color="#00f" Offset="1" />
			</LinearGradient>
		</Path>

		<Path Data="M 1 1 L 0 1 L 0 0 L 0 0" StretchMode="Fill" Width="100%" Height="100%" >
			<LinearGradient StartPoint="0.501, 0" EndPoint="0.5, 1">
				<GradientStop Color="#f00" Offset="0" />
				<GradientStop Color="#00f" Offset="1" />
			</LinearGradient>
		</Path>
	</Grid>
</App>
```

![image](https://user-images.githubusercontent.com/5551628/33615292-0cc122f4-d9da-11e7-897e-de60d1a92f29.png)

**Comment by kusma** [comment]
@drslem: What back-end? I believe this has separate implementations per platform...

**Comment by kusma** [comment]
OK. Looking at CalcGradientPoints in DotNetSurface.uno, I'm not very surprised. This code can't be correct...

**Comment by drslem** [comment]
It should just use the minimum bounding box, right?

**Comment by mortoray** [comment]
Yeah, the code looks a bit weird, but I recall we were fighting several compatibility problems on dotNet. It's also a bit tricky to get hese points right, as they're expressed in Element bounds, but may be outside or inside, but the actual drawing may not share the same bounds (see VectorLayer, or simply have an object exceeding the bounds).

**Comment by mortoray** [comment]
But yeah, that tiny variation in X should make no visual difference.
