### ISSUE TITLE
Model objects cannot be passed to ScriptClass functions

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#850]
Some ScriptClass fucntions, navigation at the moment, take objects as parameters. This isn't playing well with the model system. The object may not be attached to the tree, or it may have only been attached in this execution, thus prior to the differ running.

This makes code like `navigator.goto( new Page() )` fail (creates a repeating recursive model error).

**Comment by mortoray** [comment]
For the second point I made, in most cases I think I can get the node to be attached to the state tree. It's not enough however, since the differ may not be run by the time I call the JS function:

```
gotoNext() {
   this.next = new Page()
   nav.goto( this.next )
}
```

Possibly our ScriptClass functions might need to hook into the TreeObservable somehow. Though it'd be difficult to identify, from the function, which objects need to be managed at call time.

**Comment by Duckers** [comment]
I consider relying on scriptclasses for this type of logic is an antipattern, so I don't really see the use case here.

We should work towards minimizing the use of scriptclasses and favoring a pure declarative data flow from JS into UX components.

**Comment by mortoray** [comment]
That's easy to say, the problem is I'm really struggling to come up with a navigation system that supports animation and swiping without supporting data objects this way.

**Comment by mortoray** [comment]
I just can't see a good way to do navigation correctly with a pure state based system. I could add transition information to the pages, but this has several drawbacks:

- You'd have to update all the objects priori to doing any navigation to ensure they all do what you want
- The transition, which is ephemeral, becomes a permanent part of the state (logical problem)
- It makes a complete disconnect between prototyping and functional code. Prototypes will use primarily declarative, but without being able to intereact with this system the State system would require completely recoding all navigation.

ScriptClass and object support in navigation was intended to be the bridge between the two systems. I don't see any satisfactory solution where this doesn't work.

**Comment by Duckers** [comment]
`navigation.goto(new Page())` is a complete antipattern that violates the basic premise of FuseJS, and destroys most of the value proposition.

I would argue that transition preference information is state that should live on the pages, if no other elegant solution can be found.

I'm not worried about disconnect between "prototyping" and "functional code". Prototyping happens by building JavaScript models (perhaps through visual tooling), not UX trees.

**Comment by Duckers** [comment]
We need to build a pure state based system, where JS is king and has no knowledge of UX.

**Comment by mortoray** [comment]
Issue https://github.com/fusetools/fuselibs-public/issues/857 is likely more relevant than this one.
I'll close this for now on the assumption that if 857 is fixed this will likely also work (I can retest then)
