### ISSUE TITLE
Model property should accept dependencies

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#851]
I think we've found enough situations now where the use of dependencies as constructor arguments for model makes sense.

- Passing in UX objects. There is no other real way for the JS to interact with the UX other than these objects. It can't be done via Properties since that precludes the dependency from being used at the UX level correctly (it can't be both a dependency and a property).
- The user code is more complex when using properties.

Consider these two examples, the first is without arguments:
```
<Page ux:Class="CalendarView" Model="CalendarView/CalendarView" viewNode="calNav">
	<Router ux:Property="router"/>
	<Node ux:Property="viewNode"/>
```

The second form is with arguments.

```
<Page ux:Class="CalendarView" Model="CalendarView/CalendarView(router, calNav)">
	<Router ux:Dependency="router"/>
```

This second form has several advantages:

- You can't instantiate it without a `Router` object, it's not optional like a Property 
- It doesn't accidentally expose the `viewNode` property, which was only meant as an internal parameter to the constructor
- The JavaScript doesn't have to deal with this objects not being known or changing, they are fixed

**Comment by Duckers** [comment]
I completely agree. Constructor arguments is the way to go. 

This was in the original implementation, but as I understand, the support for expressions on `Model` has been "temporarily removed". So getting that back in to address this scenario would be good.

Another important reason/use case is being able to mock the constructur arguments (like `router` and `calNav`) for a testing that the model interacts with the external object as expected.

**Comment by mortoray** [comment]
I've marked this high, but with one limitation. We don't have to support passing object model nodes to the constructor, as that would involve the object living in more than one container. We don't support that yet (but will likely eventually).

**Comment by sebbert** [comment]
Solved in https://github.com/fusetools/fuselibs-public/pull/1036
