### ISSUE TITLE
Need a way to know if the contents of an array has changed

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#852]
There are several use-cases where I need to know if a property has been changed. Either the user editing a two-way binding, they navgiated to a new page, or changed a selection.  In the Observable world I would have used `onValueChanged`, but I don't see an equivalent for this.

**Comment by sebbert** [comment]
You can define a `$requestChange` method on your model. Note that, if this method is defined, you need to return `true` to confirm that the change should go through. This also won't work for arrays being updated.

```
class {
    $requestChange(key, value) {
        return true;
    }
}
```

**Comment by Duckers** [comment]
What context are we talking about? In JavaScript?

Are we talking about the model knowing about changes on itself? 

The intended design is that the model is *not internally reactive*. The model is only reactive when seen from the outside. The world interacts with the model through *methods*, and if the model needs to notify itself internally about changes, this must be solved by explicit logic.

The weird corner case is two-way bindings, for which there are two patterns to "respond" to changes:

* Using *getters*. Getters are automatically recomputed when relevant data visible to the class is changed, such as the content of an array. This should be a pure functional response, and is the preferred way.
* In weird corner cases, using things like `$requestChange` is possible. However, I would consider this an antipattern, and we should look for other options to achieve the goal.

@mortoray I would like to understand your exact use cases. I am not out of the gate buying the general premise that "there are use cases" that need to be solved in an explicit reactive model.

**Comment by mortoray** [comment]
I have a few cases:

- remote lookups attached to entry criteria, such as interactive search results. These cannot be reactively bound as there needs to be timing logic, and a control over requesting and cancelling results
- persisting data when it's changed
- costly filters, such as in my Netrunner card browser. This is related to the first one for interactive results. I can't rely on having a derived property that updates continuously, it's too expensive
- mapping to new UI components. For example, as you select items new editors appear on the screen. Ignoring the expensive, it's important that  the objects are preserved and new ones not created. The JS needs controls of this creation.

**Comment by mortoray** [comment]
We may not need this yet. I'll run some more tests to see if I can get away without it (some of the other High model issues being fixed might alleviate some of the problems here)
