### ISSUE TITLE
`ux:Property` does not hide Uno level properties

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#911]
At the moment any newly introduced Uno property name risks breaking `ux:Class` that uses a same named `ux:Property`.

This came up when I introduced `Element.Size`. It was being used by `AliveKit.Icon.Size` and producing a compile-time error -- one of the bindings was not referrign to the `Icon.Size` anymore but to the `Element.Size`.

It's vital that `ux:Property` names have priority and hide Uno level names. Otherwise we can't introduce any new public property without risking breaking existing code.

I'll write a simple example.

**Comment by mortoray** [comment]
This should work (it's a bit silly, but represents how a new future name could intefere with a user-defined one)

```
<App>
	<Panel ux:Class="MyComp">
		<string ux:Property="X"/>
		<Text Value="{Property this.X}"/>
	</Panel>
	
	<MyComp X="Hello"/>
</App>
```

**Comment by yupferris** [comment]
From a quick glance it looks like this isn't an error with the _output_ of the UX compiler; it's an issue with name resolution in the UX compiler itself.
