### ISSUE TITLE
PlaceholderColor does not blend alpha right on local targets

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#918]
Fuse 1.6.0 build 15070, macOS High Sierra.

Repro:
```
<App Background="Gray">
    <Panel Alignment="Center">
        <StackPanel ItemSpacing="20">
            <TextInput PlaceholderText="This black placeholder text has alpha" PlaceholderColor="#0005"/>
            <TextInput PlaceholderText="While this white text does not" PlaceholderColor="#fff2"/>
        </StackPanel>
    </Panel>
</App>
```
On local preview, both the black and white placeholders are expected to handle the alpha channel so that they're partially transparent. While the black one gets faded about right, the white one doesn't.

Native and dotnet build targets affected as well.
Neither Android nor iOS targets are affected, they render exactly as expected.

**Comment by fusebuild** [comment]
The forum thread [No alpha on placeholder text](https://www.fusetools.com/community/forums/bug_reports/no_alpha_on_placeholder_text) posted by Paul was linked to this issue.

**Comment by danhollick** [comment]
Video demonstrating the issue

[Opacity issue.mov.zip](https://github.com/fusetools/fuselibs-public/files/1635008/Opacity.issue.mov.zip)

**Comment by danhollick** [comment]
This seems to be a problem beyond `PlaceHolderColor. Happens with normal `<Text/>` elements in some cases, using both `Color` and `TextColor`.

**Comment by knatten** [comment]
@mortoray you wanted to be notified about issues related to the Sketch importer, this seems to be one. (It seems to be the cause of #86)

**Comment by mortoray** [comment]
That's Strange :tm: !?

**Comment by mortoray** [comment]
@knatten That linked issue 86 appears to be the wrong one, from wrong repo I guess?

**Comment by knatten** [comment]
Yeah, sorry. I meant https://github.com/fusetools/Sketch2Fuse/issues/86.

**Comment by mortoray** [comment]
<img width="295" alt="screen shot 2018-01-24 at 09 07 19" src="https://user-images.githubusercontent.com/1308999/35320991-08219dcc-00e6-11e8-9856-8e81ede888f7.png">

Extended example showing how it affects all non-block colors. THe other colors appear to blend with a white, or bright color, not the background. 

```
<App Background="#AAA">
    <Panel Alignment="Center">
        <StackPanel ItemSpacing="5">
            <Text Value="While this white text does not" TextColor="#fff4"/>
            <Rectangle Height="20" Color="#fff4"/>
            <Text Value="While this white text has opacity" TextColor="#fff" Opacity="0.25"/>
            <Panel Height="20"/>
            
            <Text Value="This black placeholder text has alpha" TextColor="#0004"/>
            <Rectangle Height="20" Color="#0004"/>
            <Text Value="This black text has opacity" TextColor="#000" Opacity="0.025"/>
            <Panel Height="20"/>
            
            <Text Value="While this red text @ 25%" TextColor="#f004"/>
            <Text Value="While this red text @ 50%" TextColor="#f008"/>
            <Text Value="While this red text @ 75%" TextColor="#f00c"/>
            <Text Value="While this red text @ 100%" TextColor="#f00f"/>
            <Panel Height="20"/>
            
            <Text Value="While this green text @ 25%" TextColor="#0f04"/>
            <Text Value="While this green text @ 50%" TextColor="#0f08"/>
            <Text Value="While this green text @ 75%" TextColor="#0f0c"/>
            <Text Value="While this green text @ 100%" TextColor="#0f0f"/>
            <Panel Height="20"/>
        </StackPanel>
    </Panel>
</App>
```

**Comment by mortoray** [comment]
I've located the error in the Harfbuzz blending. I should be able to fix it. I'm confirming a fix on emoji blending as well.
