### ISSUE TITLE
LinearGradient in Path shows discrete colors instead of a gradient

### ISSUE THREAD

**Issue by knatten** [fusetools/fuselibs-public#936]
The following:

```xml
<App>
    <StackPanel>
        <Path Data="M 0 0 L 1 0 L 1 1 L 0.262521114864865 1 L 0 1 L 0 0" StretchMode="Fill" Height="100">
            <LinearGradient StartPoint="0, 1" EndPoint="1">
                <GradientStop Color="#f00" Offset="0" />
                <GradientStop Color="#00f" Offset="1" />
            </LinearGradient>
        </Path>
        <Rectangle Height="100">
            <LinearGradient StartPoint="0, 1" EndPoint="1">
                <GradientStop Color="#f00" Offset="0" />
                <GradientStop Color="#00f" Offset="1" />
            </LinearGradient>
        </Rectangle>
    </StackPanel>
</App>
```

Produces this:
![screen shot 2018-01-12 at 16 02 08](https://user-images.githubusercontent.com/727543/34882046-91e8f080-f7b5-11e7-8140-a80b4e2ca4ca.png)

Tested on macOS local preview with installed Fuse, build 15133.

**Comment by mortoray** [comment]
This works on Target=Native, but not in preview (DotNet). We've had other issues with DotNet not doing gradients correctly. 

https://github.com/fusetools/fuselibs-public/issues/841

**Comment by mortoray** [comment]
<img width="787" alt="screen shot 2018-01-15 at 10 36 12" src="https://user-images.githubusercontent.com/1308999/34935962-f205e5dc-f9df-11e7-9aa1-ecf222100711.png">

It works fine for more complex layouts --- stop trying to do simple things! :P

**Comment by kusma** [comment]
To be fair, I've had a look at the code, and it's completely bonkers. I can't really imagine it working under any circumstances besides some synthetic test-cases...

**Comment by kusma** [comment]
In particular, that CalcGradientPoints-method. Stuff like `if (Math.Round(finalBoundDiff) == 1)` just screams nasty work-around for buggy code to me.

**Comment by mortoray** [comment]
I recall Noah had a lot of issues with weird corner cases in DotNet.  It also had a strange notion of what the gradient end points were, differing from the other platforms. It's unfortunate the code doesn't document what output is actually expected from this function. :(
