### ISSUE TITLE
router.goBack() breaks following multiple router.push() to the same target

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#939]
Fuse 1.6.0 build 15070, and Fuse 1.5.0 on macOS Sierra and High Sierra.

[Reported on community](https://www.fusetools.com/community/forums/bug_reports/duplicate_router_pushs_breaks_routergoback) and tested on local preview.

Repro:
```
<App>
    <JavaScript>
        module.exports = {
            test: function() {
                router.getRoute(function(r) {
                    console.log(JSON.stringify(r));
                    router.push("two", {});
                    router.push("two", {});
                });
            },
            goBack: function() {
                router.getRoute(function(r) {
                    console.log(JSON.stringify(r));
                    router.goBack();
                });
            }
        };
    </JavaScript>
    <Router ux:Name="router" />
    <Navigator DefaultPath="one">
        <Panel ux:Template="one" Color="#18f" Clicked="{test}" />
        <Panel ux:Template="two" Color="#f81" Clicked="{goBack}" />
    </Navigator>
</App>
```

The click on the second page should still bring you back to the first page, since the route hasn't changed. Debug there proves that it hasn't.

**Comment by fusebuild** [comment]
The forum thread [Duplicate router pushs breaks router.goBack()](https://www.fusetools.com/community/forums/bug_reports/duplicate_router_pushs_breaks_routergoback) posted by andrewq@redblueprint.com was linked to this issue.

**Comment by mortoray** [comment]
The route has changed. Each `push` adds a new route to the history. There is a default `Reuse` behaviour in `Navigator` that reuses the same page under certain conditions (being the path, with same properties/object is one of those conditions).  New pages can be forced with `Reuse="None"`, or one of the other values.

The user would be expected to press back twice to get back to the first page.

The JS code should not push the page twice if it doesn't want two entries in the history. There are also modify/replace operations to change the current page if desired.

**Comment by eksperts** [comment]
@mortoray "The user would be expected to press back twice to get back to the first page."

Except that this also doesn't work ^

**Comment by mortoray** [comment]
Okay. If that doesn't work then it's a defect. The call to `getRoute` that then calls `goback` is a bit weird though.

**Comment by eksperts** [comment]
That weird construct is only there for debugging purposes. The repro behaves exactly the same without `getRoute`.
