### ISSUE TITLE
Text doesn't render TextColor opacity correctly (Preview/iOS)

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#966]
The opacity of the TextColor does not apply to emoji on Desktop preview and iOS (Native and non-native).

On Android is does apply, and logiclaly it should (even if it can't apply the color).  That is, this rendering (with emoji opacity).  This is what Android shows, as well as the correct desktop preview.
<img width="194" alt="screen shot 2018-01-24 at 10 23 32" src="https://user-images.githubusercontent.com/1308999/35324321-b1895aa8-00f0-11e8-9fff-e50d5858690e.png">

Seems more correct than this one (without emoji opacity). This is what iOS currently shows.

<img width="194" alt="screen shot 2018-01-24 at 10 24 25" src="https://user-images.githubusercontent.com/1308999/35324357-c773eb58-00f0-11e8-9746-81d4334b427b.png">

**Comment by kusma** [comment]
I actually think Android is the one in the wrong here, based on how we've previously defined this to work.
