### ISSUE TITLE
Error on NativeEvent.RaiseAsync Method after upgrading to 1.6

### ISSUE THREAD

**Issue by ianychoi** [fusetools/fuselibs-public#979]
- Fuse version: 1.6.0 (build 15273)

A Korea community member reported that some existing codes using `NativeEvent.RaiseAsync Method (object[])` did not work after upgrading Fuse to 1.6.0. The error message is:

`E3128: Call to 'Fuse.Scripting.NativeEvent.RaiseAsync(Fuse.Scripting.IThreadWorker,object[])' has some invalid arguments (string)`

I tested this method using some code: https://www.fusetools.com/community/forums/howto_discussions/push_from_uno_to_javascript and https://www.fusetools.com/docs/native-interop/native-js-modules#nativeevent . I am attaching my sample code: 
[NativeEventTest.zip](https://github.com/fusetools/fuselibs-public/files/1666733/NativeEventTest.zip)
 and also the full error message.

```
Configuring  2.25 s
Compiling syntax tree
/Users/ian/Fuse/NativeEventTest/Chat.uno(28.30): E3128: Call to 'Fuse.Scripting.NativeEvent.RaiseAsync(Fuse.Scripting.IThreadWorker,object[])' has some invalid arguments (string)
/Users/ian/Fuse/NativeEventTest/Chat.uno(28,31): Error E3128: Call to 'Fuse.Scripting.NativeEvent.RaiseAsync(Fuse.Scripting.IThreadWorker,object[])' has some invalid arguments (string)/Users/ian/Fuse/NativeEventTest/Chat.uno(30.30): E3128: Call to 'Fuse.Scripting.NativeEvent.RaiseAsync(Fuse.Scripting.IThreadWorker,object[])' has some invalid arguments (string)
/Users/ian/Fuse/NativeEventTest/Chat.uno(30,31): Error E3128: Call to 'Fuse.Scripting.NativeEvent.RaiseAsync(Fuse.Scripting.IThreadWorker,object[])' has some invalid arguments (string)1.00 s

Build completed in 3.28 seconds
    2 errors
```

**Comment by ianychoi** [comment]
It seems that there have been some changes on `NativeEvent.uno`: https://github.com/fusetools/fuselibs-public/commit/e134806874dc5efbb3c000e5865d51d9ea2b92b1#diff-bb659efd421757a9eb8e118d32f2e657 . Might those changes cause the error?

**Comment by kusma** [comment]
This seems like it stems from 158e0945c591cb8d4d0e6a1080a91fb28ebd91d5.

@cbaggers: Seems like this lacks both changelog and a graceful upgrade-path (obsoletion under the old API)...
