### ISSUE TITLE
FuseJS: no transitions when pushing instances of same class

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#981]
[Reported on community](https://www.fusetools.com/community/forums/bug_reports/navigation_transitions_using_fusejs), added here for @mortoray to check out.

On the production 1.6 (and on the QA release), when trying out the new navigation method using pushing/popping objects out of a JS array, I have noticed that I can only get transitions when pushing instances of different classes. If I push consecutive new instances of the same class, even if it contains a different and random parameter, no transitions occur. Is it normal behaviour?

Please use this test app to see what I mean: http://gofile.me/6qKLQ/fn4i0tOpc.

Thanks!

**Comment by fusebuild** [comment]
The forum thread [Navigation transitions using FuseJS](https://www.fusetools.com/community/forums/bug_reports/navigation_transitions_using_fusejs) posted by Costin Bereveanu was linked to this issue.

**Comment by mortoray** [comment]
This sound like the defect fixed in https://github.com/fusetools/fuselibs-public/pull/946
We have a potential PR for 1.6 as well, https://github.com/fusetools/fuselibs-public/pull/948 , but have avoided merging it due to potential unforseen side-effects.
