### ISSUE TITLE
Gradient overflow on path

### ISSUE THREAD

**Issue by drslem** [fusetools/fuselibs-public#990]
Fuse build 15307 - local preview on Mac

This issue occurs for paths when one component (or both) of the LinearGradient Endpoint is > 1.0.
I'd expect the Path (bottom) to look the same as the Circle (top)

<img width="133" alt="screen shot 2018-01-30 at 20 48 24" src="https://user-images.githubusercontent.com/5551628/35587734-f13be2c0-05fe-11e8-84ef-702a9dcb9e60.png">

```
<App>
	<ClientPanel>
		<Circle Width="100" Height="100" Dock="Top">
			<LinearGradient StartPoint="0.4, 0.4" EndPoint="1.5, 1.5">
				<GradientStop Color="#0f0" Offset="0" />
				<GradientStop Color="#00f" Offset="1" />
			</LinearGradient>

		</Circle>

		<Path Data="M 0.5 1 C 0.7761423749 1 1 0.7761423749 1 0.5 C 1 0.2238576251 0.7761423749 0 0.5 0 C 0.2238576251 0 0 0.2238576251 0 0.5 C 0 0.7761423749 0.2238576251 1 0.5 1" Width="100" Height="100" Dock="Top" >
			<LinearGradient StartPoint="0.4, 0.4" EndPoint="1.5, 1.5">
				<GradientStop Color="#0f0" Offset="0" />
				<GradientStop Color="#00f" Offset="1" />
			</LinearGradient>
		</Path>
	</ClientPanel>
</App>
```

**Comment by mortoray** [comment]
This is one of the limitations of the way I fixed the other linear gradient drawing issues on DotNet. I optet for a solution that doesn't work well once the end points are outside of the 0..1 range. The correct solution involves a bit more effort, and considering these types of gradients can always be rewritten to be in-range I assumed it wasn't critical.

But if we need it fixed, just give it a priority.

**Comment by drslem** [comment]
I just noticed because it's really easy to make this happen using Sketch.

The normalizing could of course be done in the Sketch-importer as well, but it probably makes sense to handle it at the UX-level.

Not mission critical in any way imho, but we will want to have it fixed eventually. :)

**Comment by drslem** [comment]
Went the extra mile and checked with an actual Sketch user (Dan) who could confirm that it's fairly common to drag the endpoints all over the place. :)

**Comment by mortoray** [comment]
Okay. I'll keep it in mind when I'm annoyed at fixing other bugs. :)

Note, this is only an issue in Preview (DotNet). It's a speicfic workaround to the backend not supporting clamped gradients that results in this issue.

**Comment by mortoray** [comment]
Though you said Sketch, and I want us to have good import support... so Medium.
