### ISSUE TITLE
Uno.DateTime.ToString not consistent on device

### ISSUE THREAD

**Issue by trusis666** [fusetools/fuselibs-public#995]
[Reported on forum](https://www.fusetools.com/community/forums/bug_reports/date_system)

MacOS Siera High
Fusetools 1.5 (build 150046)
Reproduced: iPhone 7 iOs 11.2.5 and Nexus 5 Android 6.0.1

# Minimal code to reproduce:
```
<App>
    <JavaScript>
    var date = new Date();
    var string = date.toString();
    console.log(date);
    console.log(string);

    module.exports = {
        date: date,
        string: string
    }
    </JavaScript>
    <Panel Height="100">
        <StackPanel>
            <Text Alignment="Center" Row="0" Column="1" ColumnSpan="5" Value="Date: {date}"></Text>
            <Text Alignment="Center" Row="0" Column="1" ColumnSpan="5" Value="Date: {string}"></Text>
        </StackPanel>
    </Panel>
</App>
```
On the Android phone: displays "uno.DateTime" instead of "01/19/2018 03:12:10". The same happens on iOs device. 

## Fusetools studio:
<img width="240" alt="screen shot 2018-02-01 at 15 50 32" src="https://user-images.githubusercontent.com/35992243/35681958-ca41d462-0767-11e8-9179-fef9f4c57bd1.png">

## Android device
<img width="240" src="https://user-images.githubusercontent.com/35992243/35682021-fc8996ee-0767-11e8-9871-0a93569b8942.jpg">

## iOs device
<img width="240" src="https://user-images.githubusercontent.com/35992243/35682053-14b864d4-0768-11e8-9a91-aad89a4d1c6a.PNG">

**Comment by yupferris** [comment]
I've edited the title of the ticket to make it a bit more clear/specific. Thanks for the report. :)

**Comment by kusma** [comment]
I suspect that this is a problem with the DateTime class in Uno, and it's ToString method.

**Comment by yupferris** [comment]
> I suspect that this is a problem with the DateTime class in Uno, and it's ToString method.

Yep, I'm quite certain that's what this is as well.

**Comment by yupferris** [comment]
After discussing this a bit internally, it looks like we'll be able to make this consistent, but it will only print the date in UTC (thus matching the values in your test above on .net). However we can document that `toString()` is recommended for displaying dates from JS.

**Comment by fusebuild** [comment]
The forum thread ["Date" system](https://www.fusetools.com/community/forums/bug_reports/date_system) posted by mathieu@myrepublic.com.sg was linked to this issue.

**Comment by yupferris** [comment]
This was fixed in https://github.com/fusetools/uno/pull/1570.
